// Generated by eXtraCoffeeScript 1.2.0l
(function() {
  var app, channel, channels, express, id, io, port;

  express = require('express');

  app = express.createServer();

  io = require('socket.io').listen(app);

  io.set('transports', ['websocket', 'flashsocket']);

  port = 8008;

  app.configure(function() {
    app.use(express["static"](__dirname + '/public'));
    app.set('view engine', 'coffee');
    return app.register('.coffee', require('coffeekup').adapters.express);
  });

  app.get('/', function(req, res) {
    var id;
    console.log('A client has requested this route.');
    id = 0;
    return req.redirect(id);
  });

  app.get(/^\/[\w\-]+\/?$/, function(req, res) {
    return res.render('index');
  });

  channels = [];

  channels.index = {};

  id = 0;

  channel = io.of('/' + id);

  channel.on('connection', function(socket) {
    console.log('a user conn, wait for login ...', socket.id);
    return socket.on('login', function(user, callback) {
      if (!user.nick) {
        return callback({
          err: 'invalid user'
        });
      }
      socket.broadcast.emit('online', user);
      socket.on('message', function(data, callback) {
        data.user = user;
        console.log(data);
        socket.broadcast.emit('message', data);
        return callback(true);
      });
      socket.on('disconnect', function() {
        return socket.broadcast.emit('offline', user);
      });
      return callback(user);
    });
  });

  app.listen(port);

  console.log("app listening on port " + port + " ...");

}).call(this);
