// Generated by eXtraCoffeeScript 1.2.0l
(function() {
  var app, channel, channels, express, id, io, port;

  express = require('express');

  app = express.createServer();

  io = require('socket.io').listen(app);

  io.set('transports', ['websocket', 'flashsocket']);

  port = 8008;

  channels = [];

  channels.index = {};

  id = 0;

  channel = io.of(id).on('connection', function(socket) {
    var msg;
    msg = {
      that: 'only'
    };
    msg[id] = 'will get';
    socket.emit('message', msg);
    msg = {
      everyone: 'in'
    };
    msg[id] = 'will get';
    return channel.emit('message', msg);
  });

  app.configure(function() {
    app.use(express["static"](__dirname + '/public'));
    app.set('view engine', 'coffee');
    return app.register('.coffee', require('coffeekup').adapters.express);
  });

  app.get('/', function(req, res) {
    console.log('A client has requested this route.');
    id = 0;
    return req.redirect(id);
  });

  app.get(/^\/[\w\-]+\/?$/, function(req, res) {
    return res.render('index');
  });

  app.listen(port);

  console.log("app listening on port " + port + " ...");

}).call(this);
