/*
Syntax highlighting with language autodetection.
http://softwaremaniacs.org/soft/highlight/
*/
var hljs=new function(){function c(c){return c.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function a(c,a,d){return RegExp(a,"m"+(c.case_insensitive?"i":"")+(d?"g":""))}function b(c,a){for(var d="",m=0;m<c.childNodes.length;m++)if(3==c.childNodes[m].nodeType){var e=c.childNodes[m].nodeValue;a&&(e=e.replace(/\n/g,""));d+=e}else d="BR"==c.childNodes[m].nodeName?d+"\n":d+b(c.childNodes[m]);/MSIE [678]/.test(navigator.userAgent)&&(d=d.replace(/\r/g,"\n"));return d}function k(c){var a=[];(function(d,
c){for(var e=0;e<d.childNodes.length;e++)3==d.childNodes[e].nodeType?c+=d.childNodes[e].nodeValue.length:"BR"==d.childNodes[e].nodeName?c+=1:1==d.childNodes[e].nodeType&&(a.push({event:"start",offset:c,node:d.childNodes[e]}),c=arguments.callee(d.childNodes[e],c),a.push({event:"stop",offset:c,node:d.childNodes[e]}));return c})(c,0);return a}function g(a,b,d){function m(d){for(var a="<"+d.nodeName.toLowerCase(),e=0;e<d.attributes.length;e++){var b=d.attributes[e],a=a+(" "+b.nodeName.toLowerCase());
void 0!=b.value&&!1!=b.value&&null!=b.value&&(a+='="'+c(b.value)+'"')}return a+">"}for(var e=0,h="",f=[];a.length||b.length;){var g=(a.length&&b.length?a[0].offset!=b[0].offset?a[0].offset<b[0].offset?a:b:"start"==b[0].event?a:b:a.length?a:b).splice(0,1)[0],h=h+c(d.substr(e,g.offset-e)),e=g.offset;if("start"==g.event)h+=m(g.node),f.push(g.node);else if("stop"==g.event){var l=f.length;do{l--;var k=f[l],h=h+("</"+k.nodeName.toLowerCase()+">")}while(k!=g.node);for(f.splice(l,1);l<f.length;)h+=m(f[l]),
l++}}return h+=d.substr(e)}function f(){function c(d,b,e){if(!d.compiled){if(!e&&(d.beginRe=a(b,d.begin?d.begin:"\\B|\\b"),!d.end&&!d.endsWithParent&&(d.end="\\B|\\b"),d.end))d.endRe=a(b,d.end);d.illegal&&(d.illegalRe=a(b,d.illegal));void 0==d.relevance&&(d.relevance=1);d.keywords&&(d.lexemsRe=a(b,d.lexems||hljs.IDENT_RE,!0));for(var f in d.keywords)if(d.keywords.hasOwnProperty(f)){d.keywordGroups=d.keywords[f]instanceof Object?d.keywords:{keyword:d.keywords};break}d.contains||(d.contains=[]);d.compiled=
!0;for(e=0;e<d.contains.length;e++)c(d.contains[e],b,!1);d.starts&&c(d.starts,b,!1)}}for(var b in p)p.hasOwnProperty(b)&&c(p[b].defaultMode,p[b],!0)}function s(b,i){function d(c,a){if(l[c].end&&l[c].endRe.test(a))return 1;if(l[c].endsWithParent){var b=d(c-1,a);return b?b+1:0}return 0}function m(c,d){var b=l[l.length-1];if(!b.terminators){var e;e=k;for(var f=[],g=0;g<b.contains.length;g++)f.push(b.contains[g].begin);g=l.length-1;do l[g].end&&f.push(l[g].end),g--;while(l[g+1].endsWithParent);b.illegal&&
f.push(b.illegal);e=a(e,"("+f.join("|")+")",!0);b.terminators=e}b.terminators.lastIndex=d;return(b=b.terminators.exec(c))?[c.substr(d,b.index-d),b[0],!1]:[c.substr(d),"",!0]}function e(d,b){if(b.subLanguage&&p[b.subLanguage]){var a=s(b.subLanguage,d);r+=a.keyword_count;return a.value}if(b.keywords){var a="",e=0;b.lexemsRe.lastIndex=0;for(var f=b.lexemsRe.exec(d);f;){a+=c(d.substr(e,f.index-e));b:{var e=b,g=f,g=k.case_insensitive?g[0].toLowerCase():g[0],i=void 0;for(i in e.keywordGroups)if(e.keywordGroups.hasOwnProperty(i)){var m=
e.keywordGroups[i].hasOwnProperty(g);if(m){e=[i,m];break b}}e=!1}e?(r+=e[1],a+='<span class="'+e[0]+'">'+c(f[0])+"</span>"):a+=c(f[0]);e=b.lexemsRe.lastIndex;f=b.lexemsRe.exec(d)}a+=c(d.substr(e,d.length-e))}else a=c(d);return a}function h(d,b){var a=d.className?'<span class="'+d.className+'">':"";d.returnBegin?(o+=a,d.buffer=""):d.excludeBegin?(o+=c(b)+a,d.buffer=""):(o+=a,d.buffer=b);l.push(d);j+=d.relevance}function g(b,a,f){var i=l[l.length-1];if(f)return o+=e(i.buffer+b,i),!1;a:{for(f=0;f<i.contains.length;f++)if(i.contains[f].beginRe.test(a)){f=
i.contains[f];break a}f=void 0}if(f)return o+=e(i.buffer+b,i),h(f,a),f.returnBegin;if(f=d(l.length-1,a)){var m=i.className?"</span>":"";for(o=i.returnEnd?o+(e(i.buffer+b,i)+m):i.excludeEnd?o+(e(i.buffer+b,i)+m+c(a)):o+(e(i.buffer+b+a,i)+m);1<f;)m=l[l.length-2].className?"</span>":"",o+=m,f--,l.length--;b=l[l.length-1];l.length--;l[l.length-1].buffer="";b.starts&&h(b.starts,"");return i.returnEnd}if(i.illegalRe&&i.illegalRe.test(a))throw"Illegal";}f.called||(f(),f.called=!0);var k=p[b],l=[k.defaultMode],
j=0,r=0,o="";try{var n=0;k.defaultMode.buffer="";do{var q=m(i,n),v=g(q[0],q[1],q[2]),n=n+q[0].length;v||(n+=q[1].length)}while(!q[2]);if(1<l.length)throw"Illegal";return{relevance:j,keyword_count:r,value:o}}catch(u){if("Illegal"==u)return{relevance:0,keyword_count:0,value:c(i)};throw u;}}function q(b){var a={keyword_count:0,relevance:0,value:c(b)},d=a,f;for(f in p)if(p.hasOwnProperty(f)){var e=s(f,b);e.language=f;e.keyword_count+e.relevance>d.keyword_count+d.relevance&&(d=e);e.keyword_count+e.relevance>
a.keyword_count+a.relevance&&(d=a,a=e)}d.language&&(a.second_best=d);return a}function r(b,a,d){a&&(b=b.replace(/^((<[^>]+>|\t)+)/gm,function(b,d){return d.replace(/\t/g,a)}));d&&(b=b.replace(/\n/g,"<br>"));return b}function n(a,c,d){var f=b(a,d),e;a:{var h=a;e=h.className.split(/\s+/);e=e.concat(h.parentNode.className.split(/\s+/));for(h=0;h<e.length;h++){var j=e[h].replace(/^language-/,"");if(p[j]||"no-highlight"==j){e=j;break a}}e=void 0}if("no-highlight"!=e){e?h=s(e,f):(h=q(f),e=h.language);var n=
k(a);n.length&&(j=document.createElement("pre"),j.innerHTML=h.value,h.value=g(n,k(j),f));h.value=r(h.value,c,d);c=a.className;c.match("(\\s|^)(language-)?"+e+"(\\s|$)")||(c=c?c+" "+e:e);/MSIE [678]/.test(navigator.userAgent)&&"CODE"==a.tagName&&"PRE"==a.parentNode.tagName?(j=a.parentNode,d=document.createElement("div"),d.innerHTML="<pre><code>"+h.value+"</code></pre>",a=d.firstChild.firstChild,d.firstChild.className=j.className,j.parentNode.replaceChild(d.firstChild,j)):a.innerHTML=h.value;a.className=
c;a.result={language:e,kw:h.keyword_count,re:h.relevance};h.second_best&&(a.second_best={language:h.second_best.language,kw:h.second_best.keyword_count,re:h.second_best.relevance})}}function j(){if(!j.called){j.called=!0;for(var a=document.getElementsByTagName("pre"),b=0;b<a.length;b++){var d;a:{d=a[b];for(var c=0;c<d.childNodes.length;c++){var e=d.childNodes[c];if("CODE"==e.nodeName){d=e;break a}if(!(3==e.nodeType&&e.nodeValue.match(/\s+/)))break}d=void 0}d&&n(d,hljs.tabReplace)}}}var p={};this.LANGUAGES=
p;this.highlight=s;this.highlightAuto=q;this.fixMarkup=r;this.highlightBlock=n;this.initHighlighting=j;this.initHighlightingOnLoad=function(){window.addEventListener?(window.addEventListener("DOMContentLoaded",j,!1),window.addEventListener("load",j,!1)):window.attachEvent?window.attachEvent("onload",j):window.onload=j};this.IDENT_RE="[a-zA-Z][a-zA-Z0-9_]*";this.UNDERSCORE_IDENT_RE="[a-zA-Z_][a-zA-Z0-9_]*";this.NUMBER_RE="\\b\\d+(\\.\\d+)?";this.C_NUMBER_RE="\\b(0x[A-Za-z0-9]+|\\d+(\\.\\d+)?)";this.RE_STARTERS_RE=
"!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.BACKSLASH_ESCAPE={begin:"\\\\.",relevance:0};this.APOS_STRING_MODE={className:"string",begin:"'",end:"'",illegal:"\\n",contains:[this.BACKSLASH_ESCAPE],relevance:0};this.QUOTE_STRING_MODE={className:"string",begin:'"',end:'"',illegal:"\\n",contains:[this.BACKSLASH_ESCAPE],relevance:0};this.C_LINE_COMMENT_MODE={className:"comment",begin:"//",end:"$"};
this.C_BLOCK_COMMENT_MODE={className:"comment",begin:"/\\*",end:"\\*/"};this.HASH_COMMENT_MODE={className:"comment",begin:"#",end:"$"};this.NUMBER_MODE={className:"number",begin:this.NUMBER_RE,relevance:0};this.C_NUMBER_MODE={className:"number",begin:this.C_NUMBER_RE,relevance:0};this.inherit=function(a,b){var c={},f;for(f in a)c[f]=a[f];if(b)for(f in b)c[f]=b[f];return c}};
hljs.LANGUAGES.actionscript=function(){var c={className:"title",begin:"[a-zA-Z_$][a-zA-Z0-9_$]*"};return{defaultMode:{keywords:{keyword:{as:1,"break":1,"case":1,"catch":1,"class":1,"const":1,"continue":1,"default":1,"delete":1,"do":1,dynamic:5,each:1,"else":1,"extends":1,"final":1,"finally":1,"for":1,"function":1,get:1,"if":1,"implements":1,"import":1,"in":1,include:1,"instanceof":1,"interface":1,internal:1,is:1,namespace:1,"native":1,"native":1,"new":1,override:1,"package":1,"private":1,"protected":1,
"public":1,"return":1,set:1,"static":1,"super":5,"switch":1,"this":1,"throw":1,"try":1,"typeof":1,use:1,"var":1,"void":1,"while":1,"with":1},literal:{"true":1,"false":1,"null":1,undefined:1},reserved:{"abstract":0,"boolean":0,"byte":0,cast:0,"char":0,"debugger":0,"double":0,"enum":0,"export":0,"float":0,"goto":0,intrinsic:0,"long":0,prototype:0,"short":0,"synchronized":0,"throws":0,to:0,"transient":0,type:0,virtual:0,"volatile":0}},contains:[hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,hljs.C_LINE_COMMENT_MODE,
hljs.C_BLOCK_COMMENT_MODE,hljs.C_NUMBER_MODE,{className:"package",begin:"package ?",end:"{",keywords:{"package":1},contains:[c]},{className:"class",begin:"(class|interface) ",end:"{",keywords:{"class":1,"interface":1},contains:[{begin:"(implements|extends)",keywords:{"extends":1,"implements":1},relevance:5},c]},{className:"preprocessor",begin:"(import|include)\\b",end:";",keywords:{"import":1,include:1}},{className:"function",begin:"function ",end:"[{;]",keywords:{"function":1},contains:[c,{className:"params",
begin:"\\(",end:"\\)",contains:[hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,hljs.C_LINE_COMMENT_MODE,hljs.C_BLOCK_COMMENT_MODE,{className:"rest_arg",begin:"[.]{3}",end:"[a-zA-Z_$][a-zA-Z0-9_$]*",relevance:10}]},{className:"type",begin:":",end:"([*]|[a-zA-Z_$][a-zA-Z0-9_$]*)",relevance:10}]}]}}}();
hljs.LANGUAGES.apache=function(){var c={className:"number",begin:"[\\$%]\\d+"},a={className:"cbracket",begin:"[\\$%]\\{",end:"\\}"};a.contains=[a,c];return{case_insensitive:!0,defaultMode:{keywords:{keyword:{acceptfilter:1,acceptmutex:1,acceptpathinfo:1,accessfilename:1,action:1,addalt:1,addaltbyencoding:1,addaltbytype:1,addcharset:1,adddefaultcharset:1,adddescription:1,addencoding:1,addhandler:1,addicon:1,addiconbyencoding:1,addiconbytype:1,addinputfilter:1,addlanguage:1,addmoduleinfo:1,addoutputfilter:1,
addoutputfilterbytype:1,addtype:1,alias:1,aliasmatch:1,allow:1,allowconnect:1,allowencodedslashes:1,allowoverride:1,anonymous:1,anonymous_logemail:1,anonymous_mustgiveemail:1,anonymous_nouserid:1,anonymous_verifyemail:1,authbasicauthoritative:1,authbasicprovider:1,authdbduserpwquery:1,authdbduserrealmquery:1,authdbmgroupfile:1,authdbmtype:1,authdbmuserfile:1,authdefaultauthoritative:1,authdigestalgorithm:1,authdigestdomain:1,authdigestnccheck:1,authdigestnonceformat:1,authdigestnoncelifetime:1,authdigestprovider:1,
authdigestqop:1,authdigestshmemsize:1,authgroupfile:1,authldapbinddn:1,authldapbindpassword:1,authldapcharsetconfig:1,authldapcomparednonserver:1,authldapdereferencealiases:1,authldapgroupattribute:1,authldapgroupattributeisdn:1,authldapremoteuserattribute:1,authldapremoteuserisdn:1,authldapurl:1,authname:1,authnprovideralias:1,authtype:1,authuserfile:1,authzdbmauthoritative:1,authzdbmtype:1,authzdefaultauthoritative:1,authzgroupfileauthoritative:1,authzldapauthoritative:1,authzownerauthoritative:1,
authzuserauthoritative:1,balancermember:1,browsermatch:1,browsermatchnocase:1,bufferedlogs:1,cachedefaultexpire:1,cachedirlength:1,cachedirlevels:1,cachedisable:1,cacheenable:1,cachefile:1,cacheignorecachecontrol:1,cacheignoreheaders:1,cacheignorenolastmod:1,cacheignorequerystring:1,cachelastmodifiedfactor:1,cachemaxexpire:1,cachemaxfilesize:1,cacheminfilesize:1,cachenegotiateddocs:1,cacheroot:1,cachestorenostore:1,cachestoreprivate:1,cgimapextension:1,charsetdefault:1,charsetoptions:1,charsetsourceenc:1,
checkcaseonly:1,checkspelling:1,chrootdir:1,contentdigest:1,cookiedomain:1,cookieexpires:1,cookielog:1,cookiename:1,cookiestyle:1,cookietracking:1,coredumpdirectory:1,customlog:1,dav:1,davdepthinfinity:1,davgenericlockdb:1,davlockdb:1,davmintimeout:1,dbdexptime:1,dbdkeep:1,dbdmax:1,dbdmin:1,dbdparams:1,dbdpersist:1,dbdpreparesql:1,dbdriver:1,defaulticon:1,defaultlanguage:1,defaulttype:1,deflatebuffersize:1,deflatecompressionlevel:1,deflatefilternote:1,deflatememlevel:1,deflatewindowsize:1,deny:1,
directoryindex:1,directorymatch:1,directoryslash:1,documentroot:1,dumpioinput:1,dumpiologlevel:1,dumpiooutput:1,enableexceptionhook:1,enablemmap:1,enablesendfile:1,errordocument:1,errorlog:1,example:1,expiresactive:1,expiresbytype:1,expiresdefault:1,extendedstatus:1,extfilterdefine:1,extfilteroptions:1,fileetag:1,filterchain:1,filterdeclare:1,filterprotocol:1,filterprovider:1,filtertrace:1,forcelanguagepriority:1,forcetype:1,forensiclog:1,gracefulshutdowntimeout:1,group:1,header:1,headername:1,hostnamelookups:1,
identitycheck:1,identitychecktimeout:1,imapbase:1,imapdefault:1,imapmenu:1,include:1,indexheadinsert:1,indexignore:1,indexoptions:1,indexorderdefault:1,indexstylesheet:1,isapiappendlogtoerrors:1,isapiappendlogtoquery:1,isapicachefile:1,isapifakeasync:1,isapilognotsupported:1,isapireadaheadbuffer:1,keepalive:1,keepalivetimeout:1,languagepriority:1,ldapcacheentries:1,ldapcachettl:1,ldapconnectiontimeout:1,ldapopcacheentries:1,ldapopcachettl:1,ldapsharedcachefile:1,ldapsharedcachesize:1,ldaptrustedclientcert:1,
ldaptrustedglobalcert:1,ldaptrustedmode:1,ldapverifyservercert:1,limitinternalrecursion:1,limitrequestbody:1,limitrequestfields:1,limitrequestfieldsize:1,limitrequestline:1,limitxmlrequestbody:1,listen:1,listenbacklog:1,loadfile:1,loadmodule:1,lockfile:1,logformat:1,loglevel:1,maxclients:1,maxkeepaliverequests:1,maxmemfree:1,maxrequestsperchild:1,maxrequestsperthread:1,maxspareservers:1,maxsparethreads:1,maxthreads:1,mcachemaxobjectcount:1,mcachemaxobjectsize:1,mcachemaxstreamingbuffer:1,mcacheminobjectsize:1,
mcacheremovalalgorithm:1,mcachesize:1,metadir:1,metafiles:1,metasuffix:1,mimemagicfile:1,minspareservers:1,minsparethreads:1,mmapfile:1,mod_gzip_on:1,mod_gzip_add_header_count:1,mod_gzip_keep_workfiles:1,mod_gzip_dechunk:1,mod_gzip_min_http:1,mod_gzip_minimum_file_size:1,mod_gzip_maximum_file_size:1,mod_gzip_maximum_inmem_size:1,mod_gzip_temp_dir:1,mod_gzip_item_include:1,mod_gzip_item_exclude:1,mod_gzip_command_version:1,mod_gzip_can_negotiate:1,mod_gzip_handle_methods:1,mod_gzip_static_suffix:1,
mod_gzip_send_vary:1,mod_gzip_update_static:1,modmimeusepathinfo:1,multiviewsmatch:1,namevirtualhost:1,noproxy:1,nwssltrustedcerts:1,nwsslupgradeable:1,options:1,order:1,passenv:1,pidfile:1,protocolecho:1,proxybadheader:1,proxyblock:1,proxydomain:1,proxyerroroverride:1,proxyftpdircharset:1,proxyiobuffersize:1,proxymaxforwards:1,proxypass:1,proxypassinterpolateenv:1,proxypassmatch:1,proxypassreverse:1,proxypassreversecookiedomain:1,proxypassreversecookiepath:1,proxypreservehost:1,proxyreceivebuffersize:1,
proxyremote:1,proxyremotematch:1,proxyrequests:1,proxyset:1,proxystatus:1,proxytimeout:1,proxyvia:1,readmename:1,receivebuffersize:1,redirect:1,redirectmatch:1,redirectpermanent:1,redirecttemp:1,removecharset:1,removeencoding:1,removehandler:1,removeinputfilter:1,removelanguage:1,removeoutputfilter:1,removetype:1,requestheader:1,require:2,rewritebase:1,rewritecond:10,rewriteengine:1,rewritelock:1,rewritelog:1,rewriteloglevel:1,rewritemap:1,rewriteoptions:1,rewriterule:10,rlimitcpu:1,rlimitmem:1,rlimitnproc:1,
satisfy:1,scoreboardfile:1,script:1,scriptalias:1,scriptaliasmatch:1,scriptinterpretersource:1,scriptlog:1,scriptlogbuffer:1,scriptloglength:1,scriptsock:1,securelisten:1,seerequesttail:1,sendbuffersize:1,serveradmin:1,serveralias:1,serverlimit:1,servername:1,serverpath:1,serverroot:1,serversignature:1,servertokens:1,setenv:1,setenvif:1,setenvifnocase:1,sethandler:1,setinputfilter:1,setoutputfilter:1,ssienableaccess:1,ssiendtag:1,ssierrormsg:1,ssistarttag:1,ssitimeformat:1,ssiundefinedecho:1,sslcacertificatefile:1,
sslcacertificatepath:1,sslcadnrequestfile:1,sslcadnrequestpath:1,sslcarevocationfile:1,sslcarevocationpath:1,sslcertificatechainfile:1,sslcertificatefile:1,sslcertificatekeyfile:1,sslciphersuite:1,sslcryptodevice:1,sslengine:1,sslhonorciperorder:1,sslmutex:1,ssloptions:1,sslpassphrasedialog:1,sslprotocol:1,sslproxycacertificatefile:1,sslproxycacertificatepath:1,sslproxycarevocationfile:1,sslproxycarevocationpath:1,sslproxyciphersuite:1,sslproxyengine:1,sslproxymachinecertificatefile:1,sslproxymachinecertificatepath:1,
sslproxyprotocol:1,sslproxyverify:1,sslproxyverifydepth:1,sslrandomseed:1,sslrequire:1,sslrequiressl:1,sslsessioncache:1,sslsessioncachetimeout:1,sslusername:1,sslverifyclient:1,sslverifydepth:1,startservers:1,startthreads:1,substitute:1,suexecusergroup:1,threadlimit:1,threadsperchild:1,threadstacksize:1,timeout:1,traceenable:1,transferlog:1,typesconfig:1,unsetenv:1,usecanonicalname:1,usecanonicalphysicalport:1,user:1,userdir:1,virtualdocumentroot:1,virtualdocumentrootip:1,virtualscriptalias:1,virtualscriptaliasip:1,
win32disableacceptex:1,xbithack:1},literal:{on:1,off:1}},contains:[hljs.HASH_COMMENT_MODE,{className:"sqbracket",begin:"\\s\\[",end:"\\]$"},a,c,{className:"tag",begin:"</?",end:">"},hljs.QUOTE_STRING_MODE]}}}();
hljs.LANGUAGES.bash=function(){var c={"true":1,"false":1},a={className:"variable",begin:"\\$([a-zA-Z0-9_]+)\\b"},b={className:"variable",begin:"\\$\\{(([^}])|(\\\\}))+\\}",contains:[hljs.C_NUMBER_MODE]},k={className:"string",begin:'"',end:'"',illegal:"\\n",contains:[hljs.BACKSLASH_ESCAPE,a,b],relevance:0},g={className:"string",begin:"'",end:"'",relevance:0},f={className:"test_condition",begin:"",end:"",contains:[k,g,a,b,hljs.C_NUMBER_MODE],keywords:{literal:c},relevance:0};return{defaultMode:{keywords:{keyword:{"if":1,
then:1,"else":1,fi:1,"for":1,"break":1,"continue":1,"while":1,"in":1,"do":1,done:1,echo:1,exit:1,"return":1,set:1,declare:1},literal:c},contains:[{className:"shebang",begin:"(#!\\/bin\\/bash)|(#!\\/bin\\/sh)",relevance:10},a,b,hljs.HASH_COMMENT_MODE,hljs.C_NUMBER_MODE,k,g,hljs.inherit(f,{begin:"\\[ ",end:" \\]",relevance:0}),hljs.inherit(f,{begin:"\\[\\[ ",end:" \\]\\]"})]}}}();
hljs.LANGUAGES.cmake={case_insensitive:!0,defaultMode:{keywords:{add_custom_command:2,add_custom_target:2,add_definitions:2,add_dependencies:2,add_executable:2,add_library:2,add_subdirectory:2,add_executable:2,add_library:2,add_subdirectory:2,add_test:2,aux_source_directory:2,"break":1,build_command:2,cmake_minimum_required:3,cmake_policy:3,configure_file:1,create_test_sourcelist:1,define_property:1,"else":1,elseif:1,enable_language:2,enable_testing:2,endforeach:1,endfunction:1,endif:1,endmacro:1,
endwhile:1,execute_process:2,"export":1,find_file:1,find_library:2,find_package:2,find_path:1,find_program:1,fltk_wrap_ui:2,foreach:1,"function":1,get_cmake_property:3,get_directory_property:1,get_filename_component:1,get_property:1,get_source_file_property:1,get_target_property:1,get_test_property:1,"if":1,include:1,include_directories:2,include_external_msproject:1,include_regular_expression:2,install:1,link_directories:1,load_cache:1,load_command:1,macro:1,mark_as_advanced:1,message:1,option:1,
output_required_files:1,project:1,qt_wrap_cpp:2,qt_wrap_ui:2,remove_definitions:2,"return":1,separate_arguments:1,set:1,set_directory_properties:1,set_property:1,set_source_files_properties:1,set_target_properties:1,set_tests_properties:1,site_name:1,source_group:1,string:1,target_link_libraries:2,try_compile:2,try_run:2,unset:1,variable_watch:2,"while":1,build_name:1,exec_program:1,export_library_dependencies:1,install_files:1,install_programs:1,install_targets:1,link_libraries:1,make_directory:1,
remove:1,subdir_depends:1,subdirs:1,use_mangled_mesa:1,utility_source:1,variable_requires:1,write_file:1},contains:[{className:"envvar",begin:"\\${",end:"}"},hljs.HASH_COMMENT_MODE,hljs.QUOTE_STRING_MODE,hljs.NUMBER_MODE]}};
hljs.LANGUAGES.coffee=function(){var c={keyword:{"in":1,"if":1,"for":1,"while":1,"finally":1,"new":1,"do":1,"return":1,"else":1,"break":1,"catch":1,"instanceof":1,"throw":1,"try":1,"this":1,"switch":1,"continue":1,"typeof":1,"delete":1,"return":1,"debugger":1,"class":1,"extends":1,"super":1,then:1,unless:1,until:1,loop:2,of:2,by:1,when:2,and:1,or:1,is:1,isnt:2,not:1},literal:{"true":1,"false":1,"null":1,undefined:1,yes:1,no:1,on:1,off:1},reserved:{"case":1,"default":1,"function":1,"var":1,"void":1,
"with":1,"const":1,let:1,"enum":1,"export":1,"import":1,"native":1,__hasProp:1,__extends:1,__slice:1,__bind:1,__indexOf:1}},a={className:"string",begin:"'",end:"'",relevance:0},b={className:"string",begin:'"',end:'"',relevance:0,contains:[hljs.BACKSLASH_ESCAPE,{className:"subst",begin:"#\\{",end:"}",keywords:c,contains:[hljs.C_NUMBER_MODE]}]};return{defaultMode:{keywords:c,contains:[{className:"comment",begin:"###",end:"###",relevance:5},hljs.C_NUMBER_MODE,hljs.HASH_COMMENT_MODE,a,b,{className:"params",
begin:"\\(",end:"\\)",keywords:c,contains:[hljs.C_NUMBER_MODE,a,b]},{className:"function",begin:"(->|=>)",end:hljs.IMMEIDATE_RE,relevance:10}]}}}();
hljs.LANGUAGES.cpp=function(){var c={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,
typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,
unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}},a={className:"stl_container",begin:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",end:">",keywords:c,relevance:10};a.contains=[a];return{defaultMode:{keywords:c,illegal:"</",contains:[hljs.C_LINE_COMMENT_MODE,hljs.C_BLOCK_COMMENT_MODE,hljs.QUOTE_STRING_MODE,{className:"string",begin:"'",end:"[^\\\\]'",illegal:"[^\\\\][^']"},hljs.C_NUMBER_MODE,
{className:"preprocessor",begin:"#",end:"$"},a]}}}();
hljs.LANGUAGES.cs={defaultMode:{keywords:{"abstract":1,as:1,base:1,bool:1,"break":1,"byte":1,"case":1,"catch":1,"char":1,checked:1,"class":1,"const":1,"continue":1,decimal:1,"default":1,delegate:1,"do":1,"do":1,"double":1,"else":1,"enum":1,event:1,explicit:1,extern:1,"false":1,"finally":1,fixed:1,"float":1,"for":1,foreach:1,"goto":1,"if":1,implicit:1,"in":1,"int":1,"interface":1,internal:1,is:1,lock:1,"long":1,namespace:1,"new":1,"null":1,object:1,operator:1,out:1,override:1,params:1,"private":1,
"protected":1,"public":1,readonly:1,ref:1,"return":1,sbyte:1,sealed:1,"short":1,sizeof:1,stackalloc:1,"static":1,string:1,struct:1,"switch":1,"this":1,"throw":1,"true":1,"try":1,"typeof":1,uint:1,ulong:1,unchecked:1,unsafe:1,ushort:1,using:1,virtual:1,"volatile":1,"void":1,"while":1,ascending:1,descending:1,from:1,get:1,group:1,into:1,join:1,let:1,orderby:1,partial:1,select:1,set:1,value:1,"var":1,where:1,yield:1},contains:[{className:"comment",begin:"///",end:"$",returnBegin:!0,contains:[{className:"xmlDocTag",
begin:"///|<\!--|--\>"},{className:"xmlDocTag",begin:"</?",end:">"}]},hljs.C_LINE_COMMENT_MODE,hljs.C_BLOCK_COMMENT_MODE,{className:"preprocessor",begin:"#",end:"$",keywords:{"if":1,"else":1,elif:1,endif:1,define:1,undef:1,warning:1,error:1,line:1,region:1,endregion:1,pragma:1,checksum:1}},{className:"string",begin:'@"',end:'"',contains:[{begin:'""'}]},hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,hljs.C_NUMBER_MODE]}};
hljs.LANGUAGES.css=function(){var c={className:"function",begin:hljs.IDENT_RE+"\\(",end:"\\)",contains:[{endsWithParent:!0,excludeEnd:!0,contains:[hljs.NUMBER_MODE,hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE]}]};return{case_insensitive:!0,defaultMode:{illegal:"[=/|']",contains:[hljs.C_BLOCK_COMMENT_MODE,{className:"id",begin:"\\#[A-Za-z0-9_-]+"},{className:"class",begin:"\\.[A-Za-z0-9_-]+",relevance:0},{className:"attr_selector",begin:"\\[",end:"\\]",illegal:"$"},{className:"pseudo",begin:":(:)?[a-zA-Z0-9\\_\\-\\+\\(\\)\\\"\\']+"},
{className:"at_rule",begin:"@(font-face|page)",lexems:"[a-z-]+",keywords:{"font-face":1,page:1}},{className:"at_rule",begin:"@",end:"[{;]",excludeEnd:!0,keywords:{"import":1,page:1,media:1,charset:1},contains:[c,hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,hljs.NUMBER_MODE]},{className:"tag",begin:hljs.IDENT_RE,relevance:0},{className:"rules",begin:"{",end:"}",illegal:"[^\\s]",relevance:0,contains:[hljs.C_BLOCK_COMMENT_MODE,{className:"rule",begin:"[^\\s]",returnBegin:!0,end:";",endsWithParent:!0,
contains:[{className:"attribute",begin:"[A-Z\\_\\.\\-]+",end:":",excludeEnd:!0,illegal:"[^\\s]",starts:{className:"value",endsWithParent:!0,excludeEnd:!0,contains:[c,hljs.NUMBER_MODE,hljs.QUOTE_STRING_MODE,hljs.APOS_STRING_MODE,hljs.C_BLOCK_COMMENT_MODE,{className:"hexcolor",begin:"\\#[0-9A-F]+"},{className:"important",begin:"!important"}]}}]}]}]}}}();
hljs.LANGUAGES.diff={case_insensitive:!0,defaultMode:{contains:[{className:"chunk",begin:"^\\@\\@ +\\-\\d+,\\d+ +\\+\\d+,\\d+ +\\@\\@$",relevance:10},{className:"chunk",begin:"^\\*\\*\\* +\\d+,\\d+ +\\*\\*\\*\\*$",relevance:10},{className:"chunk",begin:"^\\-\\-\\- +\\d+,\\d+ +\\-\\-\\-\\-$",relevance:10},{className:"header",begin:"Index: ",end:"$"},{className:"header",begin:"=====",end:"=====$"},{className:"header",begin:"^\\-\\-\\-",end:"$"},{className:"header",begin:"^\\*{3} ",end:"$"},{className:"header",
begin:"^\\+\\+\\+",end:"$"},{className:"header",begin:"\\*{5}",end:"\\*{5}$"},{className:"addition",begin:"^\\+",end:"$"},{className:"deletion",begin:"^\\-",end:"$"},{className:"change",begin:"^\\!",end:"$"}]}};
hljs.LANGUAGES.dos={case_insensitive:!0,defaultMode:{keywords:{flow:{"if":1,"else":1,"goto":1,"for":1,"in":1,"do":1,call:1,exit:1,not:1,exist:1,errorlevel:1,defined:1,equ:1,neq:1,lss:1,leq:1,gtr:1,geq:1},keyword:{shift:1,cd:1,dir:1,echo:1,setlocal:1,endlocal:1,set:1,pause:1,copy:1},stream:{prn:1,nul:1,lpt3:1,lpt2:1,lpt1:1,con:1,com4:1,com3:1,com2:1,com1:1,aux:1},winutils:{ping:1,net:1,ipconfig:1,taskkill:1,xcopy:1,ren:1,del:1}},contains:[{className:"envvar",begin:"%[^ ]+?%"},{className:"number",begin:"\\b\\d+",
relevance:0},{className:"comment",begin:"@?rem",end:"$"}]}};
hljs.LANGUAGES.go=function(){return{defaultMode:{keywords:{keyword:{"break":1,"default":1,func:1,"interface":1,select:1,"case":1,map:1,struct:1,chan:1,"else":1,"goto":1,"package":1,"switch":1,"const":1,fallthrough:1,"if":1,range:1,type:1,"continue":1,"for":1,"import":1,"return":1,"var":1,go:1,defer:1},constant:{"true":1,"false":1,iota:1,nil:1},typename:{bool:1,"byte":1,complex64:1,complex128:1,float32:1,float64:1,int8:1,int16:1,int32:1,int64:1,string:1,uint8:1,uint16:1,uint32:1,uint64:1,"int":1,uint:1,
uintptr:1},built_in:{append:1,cap:1,close:1,complex:1,copy:1,imag:1,len:1,make:1,"new":1,panic:1,print:1,println:1,real:1,recover:1}},illegal:"</",contains:[hljs.C_LINE_COMMENT_MODE,hljs.C_BLOCK_COMMENT_MODE,hljs.QUOTE_STRING_MODE,{className:"string",begin:"'",end:"[^\\\\]'",relevance:0},{className:"string",begin:"`",end:"[^\\\\]`"},{className:"number",begin:"[^a-zA-Z_0-9](\\-|\\+)?\\d+(\\.\\d+|\\/\\d+)?((d|e|f|l|s)(\\+|\\-)?\\d+)?",relevance:0},hljs.C_NUMBER_MODE]}}}();
hljs.LANGUAGES.ini={case_insensitive:!0,defaultMode:{illegal:"[^\\s]",contains:[{className:"comment",begin:";",end:"$"},{className:"title",begin:"^\\[",end:"\\]"},{className:"setting",begin:"^[a-z0-9_\\[\\]]+[ \\t]*=[ \\t]*",end:"$",contains:[{className:"value",endsWithParent:!0,keywords:{on:1,off:1,"true":1,"false":1,yes:1,no:1},contains:[hljs.QUOTE_STRING_MODE,hljs.NUMBER_MODE]}]}]}};
hljs.LANGUAGES.java={defaultMode:{keywords:{"false":1,"synchronized":1,"int":1,"abstract":1,"float":1,"private":1,"char":1,"interface":1,"boolean":1,"static":1,"null":1,"if":1,"const":1,"for":1,"true":1,"while":1,"long":1,"throw":1,strictfp:1,"finally":1,"protected":1,"extends":1,"import":1,"native":1,"final":1,"implements":1,"return":1,"void":1,"enum":1,"else":1,"break":1,"transient":1,"new":1,"catch":1,"instanceof":1,"byte":1,"super":1,"class":1,"volatile":1,"case":1,assert:1,"short":1,"package":1,
"default":1,"double":1,"public":1,"try":1,"this":1,"switch":1,"continue":1,"throws":1},contains:[{className:"javadoc",begin:"/\\*\\*",end:"\\*/",contains:[{className:"javadoctag",begin:"@[A-Za-z]+"}],relevance:10},hljs.C_LINE_COMMENT_MODE,hljs.C_BLOCK_COMMENT_MODE,hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,{className:"class",begin:"(class |interface )",end:"{",keywords:{"class":1,"interface":1},illegal:":",contains:[{begin:"(implements|extends)",keywords:{"extends":1,"implements":1},relevance:10},
{className:"title",begin:hljs.UNDERSCORE_IDENT_RE}]},hljs.C_NUMBER_MODE,{className:"annotation",begin:"@[A-Za-z]+"}]}};
hljs.LANGUAGES.javascript={defaultMode:{keywords:{keyword:{"in":1,"if":1,"for":1,"while":1,"finally":1,"var":1,"new":1,"function":1,"do":1,"return":1,"void":1,"else":1,"break":1,"catch":1,"instanceof":1,"with":1,"throw":1,"case":1,"default":1,"try":1,"this":1,"switch":1,"continue":1,"typeof":1,"delete":1},literal:{"true":1,"false":1,"null":1}},contains:[hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,hljs.C_LINE_COMMENT_MODE,hljs.C_BLOCK_COMMENT_MODE,hljs.C_NUMBER_MODE,{begin:"("+hljs.RE_STARTERS_RE+
"|case|return|throw)\\s*",keywords:{"return":1,"throw":1,"case":1},contains:[hljs.C_LINE_COMMENT_MODE,hljs.C_BLOCK_COMMENT_MODE,{className:"regexp",begin:"/",end:"/[gim]*",contains:[{begin:"\\\\/"}]}],relevance:0},{className:"function",begin:"\\bfunction\\b",end:"{",keywords:{"function":1},contains:[{className:"title",begin:"[A-Za-z$_][0-9A-Za-z$_]*"},{className:"params",begin:"\\(",end:"\\)",contains:[hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,hljs.C_LINE_COMMENT_MODE,hljs.C_BLOCK_COMMENT_MODE]}]}]}};
hljs.LANGUAGES.lisp=function(){var c={className:"literal",begin:"\\b(t{1}|nil)\\b"},a={className:"number",begin:"(\\-|\\+)?\\d+(\\.\\d+|\\/\\d+)?((d|e|f|l|s)(\\+|\\-)?\\d+)?"},b={className:"number",begin:"#b[0-1]+(/[0-1]+)?"},k={className:"number",begin:"#o[0-7]+(/[0-7]+)?"},g={className:"number",begin:"#x[0-9a-f]+(/[0-9a-f]+)?"},f={className:"number",begin:"#c\\((\\-|\\+)?\\d+(\\.\\d+|\\/\\d+)?((d|e|f|l|s)(\\+|\\-)?\\d+)? +(\\-|\\+)?\\d+(\\.\\d+|\\/\\d+)?((d|e|f|l|s)(\\+|\\-)?\\d+)?",end:"\\)"},
s={className:"string",begin:'"',end:'"',contains:[hljs.BACKSLASH_ESCAPE],relevance:0},q={className:"comment",begin:";",end:"$"},r={className:"variable",begin:"\\*",end:"\\*"},n={className:"keyword",begin:"[:&][a-zA-Z_\\-\\+\\*\\/\\<\\=\\>\\&\\#][a-zA-Z0-9_\\-\\+\\*\\/\\<\\=\\>\\&\\#]*"},j={begin:"\\(",end:"\\)"};j.contains=[j,c,a,b,k,g,f,s];var p={className:"quoted",begin:"['`]\\(",end:"\\)",contains:[a,b,k,g,f,s,r,n,j]},j={className:"quoted",begin:"\\(quote ",end:"\\)",keywords:{title:{quote:1}},
contains:[a,b,k,g,f,s,r,n,j]},t={className:"list",begin:"\\(",end:"\\)"},i={className:"body",endsWithParent:!0,excludeEnd:!0};t.contains=[{className:"title",begin:"[a-zA-Z_\\-\\+\\*\\/\\<\\=\\>\\&\\#][a-zA-Z0-9_\\-\\+\\*\\/\\<\\=\\>\\&\\#]*"},i];i.contains=[p,j,t,c,a,b,k,g,f,s,q,r,n];return{case_insensitive:!0,defaultMode:{illegal:"[^\\s]",contains:[c,a,b,k,g,f,s,q,p,j,t]}}}();
hljs.LANGUAGES.lua=function(){var c={begin:"\\[=*\\[",end:"\\]=*\\]"};c.contains=[c];var a={className:"comment",begin:"--(?!\\[=*\\[)",end:"$"},b={className:"comment",begin:"--\\[=*\\[",end:"\\]=*\\]",contains:[c],relevance:10};return{defaultMode:{lexems:hljs.UNDERSCORE_IDENT_RE,keywords:{keyword:{and:1,"break":1,"do":1,"else":1,elseif:1,end:1,"false":1,"for":1,"if":1,"in":1,local:1,nil:1,not:1,or:1,repeat:1,"return":1,then:1,"true":1,until:1,"while":1},built_in:{_G:1,_VERSION:1,assert:1,collectgarbage:1,
dofile:1,error:1,getfenv:1,getmetatable:1,ipairs:1,load:1,loadfile:1,loadstring:1,module:1,next:1,pairs:1,pcall:1,print:1,rawequal:1,rawget:1,rawset:1,require:1,select:1,setfenv:1,setmetatable:1,tonumber:1,tostring:1,type:1,unpack:1,xpcall:1,coroutine:1,debug:1,io:1,math:1,os:1,"package":1,string:1,table:1}},contains:[a,b,{className:"function",begin:"\\bfunction\\b",end:"\\)",keywords:{"function":1},contains:[{className:"title",begin:"([_a-zA-Z]\\w*\\.)*([_a-zA-Z]\\w*:)?[_a-zA-Z]\\w*"},{className:"params",
begin:"\\(",endsWithParent:!0,contains:[a,b]},a,b]},hljs.C_NUMBER_MODE,hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,{className:"string",begin:"\\[=*\\[",end:"\\]=*\\]",contains:[c],relevance:10}]}}}();
hljs.LANGUAGES.markdown={case_insensitive:!0,defaultMode:{contains:[{className:"header",begin:"^#{1,3}",end:"$"},{className:"header",begin:"^.+?\\n[=-]{2,}$"},{begin:"<",end:">",subLanguage:"xml"},{className:"bullet",begin:"^([*+-]|(\\d+.))\\s+"},{className:"strong",begin:"[*_]{2}.+?[*_]{2}"},{className:"emphasis",begin:"[*_].+?[*_]"},{className:"blockquote",begin:"^>\\s+",end:"$"},{className:"code",begin:"`.+?`"},{className:"code",begin:"^    ",end:"$",relevance:0},{className:"horizontal_rule",begin:"^-{3,}",
end:"$"},{begin:"\\[.+?\\]\\(.+?\\)",returnBegin:!0,contains:[{className:"link_label",begin:"\\[.+\\]"},{className:"link_url",begin:"\\(",end:"\\)",excludeBegin:!0,excludeEnd:!0}]}]}};
hljs.LANGUAGES.nginx=function(){var c={className:"variable",begin:"\\$\\d+"},a={className:"variable",begin:"\\${",end:"}"},b={className:"variable",begin:"[\\$\\@]"+hljs.UNDERSCORE_IDENT_RE};return{defaultMode:{contains:[hljs.HASH_COMMENT_MODE,{begin:hljs.UNDERSCORE_IDENT_RE,end:";|{",returnEnd:!0,keywords:{accept_mutex:1,accept_mutex_delay:1,access_log:1,add_after_body:1,add_before_body:1,add_header:1,addition_types:1,alias:1,allow:1,ancient_browser:1,ancient_browser:1,ancient_browser_value:1,ancient_browser_value:1,
auth_basic:1,auth_basic_user_file:1,autoindex:1,autoindex_exact_size:1,autoindex_localtime:1,"break":1,charset:1,charset:1,charset_map:1,charset_map:1,charset_types:1,charset_types:1,client_body_buffer_size:1,client_body_in_file_only:1,client_body_in_single_buffer:1,client_body_temp_path:1,client_body_timeout:1,client_header_buffer_size:1,client_header_timeout:1,client_max_body_size:1,connection_pool_size:1,connections:1,create_full_put_path:1,daemon:1,dav_access:1,dav_methods:1,debug_connection:1,
debug_points:1,default_type:1,deny:1,directio:1,directio_alignment:1,echo:1,echo_after_body:1,echo_before_body:1,echo_blocking_sleep:1,echo_duplicate:1,echo_end:1,echo_exec:1,echo_flush:1,echo_foreach_split:1,echo_location:1,echo_location_async:1,echo_read_request_body:1,echo_request_body:1,echo_reset_timer:1,echo_sleep:1,echo_subrequest:1,echo_subrequest_async:1,empty_gif:1,empty_gif:1,env:1,error_log:1,error_log:1,error_page:1,events:1,expires:1,fastcgi_bind:1,fastcgi_buffer_size:1,fastcgi_buffers:1,
fastcgi_busy_buffers_size:1,fastcgi_cache:1,fastcgi_cache_key:1,fastcgi_cache_methods:1,fastcgi_cache_min_uses:1,fastcgi_cache_path:1,fastcgi_cache_use_stale:1,fastcgi_cache_valid:1,fastcgi_catch_stderr:1,fastcgi_connect_timeout:1,fastcgi_hide_header:1,fastcgi_ignore_client_abort:1,fastcgi_ignore_headers:1,fastcgi_index:1,fastcgi_intercept_errors:1,fastcgi_max_temp_file_size:1,fastcgi_next_upstream:1,fastcgi_param:1,fastcgi_pass:1,fastcgi_pass_header:1,fastcgi_pass_request_body:1,fastcgi_pass_request_headers:1,
fastcgi_read_timeout:1,fastcgi_send_lowat:1,fastcgi_send_timeout:1,fastcgi_split_path_info:1,fastcgi_store:1,fastcgi_store_access:1,fastcgi_temp_file_write_size:1,fastcgi_temp_path:1,fastcgi_upstream_fail_timeout:1,fastcgi_upstream_max_fails:1,flv:1,geo:1,geo:1,geoip_city:1,geoip_country:1,gzip:1,gzip_buffers:1,gzip_comp_level:1,gzip_disable:1,gzip_hash:1,gzip_http_version:1,gzip_min_length:1,gzip_no_buffer:1,gzip_proxied:1,gzip_static:1,gzip_types:1,gzip_vary:1,gzip_window:1,http:1,"if":1,if_modified_since:1,
ignore_invalid_headers:1,image_filter:1,image_filter_buffer:1,image_filter_jpeg_quality:1,image_filter_transparency:1,include:1,index:1,internal:1,ip_hash:1,js:1,js_load:1,js_require:1,js_utf8:1,keepalive_requests:1,keepalive_timeout:1,kqueue_changes:1,kqueue_events:1,large_client_header_buffers:1,limit_conn:1,limit_conn_log_level:1,limit_except:1,limit_rate:1,limit_rate_after:1,limit_req:1,limit_req_log_level:1,limit_req_zone:1,limit_zone:1,lingering_time:1,lingering_timeout:1,listen:1,location:1,
lock_file:1,log_format:1,log_not_found:1,log_subrequest:1,map:1,map_hash_bucket_size:1,map_hash_max_size:1,master_process:1,memcached_bind:1,memcached_buffer_size:1,memcached_connect_timeout:1,memcached_next_upstream:1,memcached_pass:1,memcached_read_timeout:1,memcached_send_timeout:1,memcached_upstream_fail_timeout:1,memcached_upstream_max_fails:1,merge_slashes:1,min_delete_depth:1,modern_browser:1,modern_browser:1,modern_browser_value:1,modern_browser_value:1,more_clear_headers:1,more_clear_input_headers:1,
more_set_headers:1,more_set_input_headers:1,msie_padding:1,msie_refresh:1,multi_accept:1,open_file_cache:1,open_file_cache_errors:1,open_file_cache_events:1,open_file_cache_min_uses:1,open_file_cache_retest:1,open_file_cache_valid:1,open_log_file_cache:1,optimize_server_names:1,output_buffers:1,override_charset:1,override_charset:1,perl:1,perl_modules:1,perl_require:1,perl_set:1,pid:1,port_in_redirect:1,post_action:1,postpone_gzipping:1,postpone_output:1,proxy_bind:1,proxy_buffer_size:1,proxy_buffering:1,
proxy_buffers:1,proxy_busy_buffers_size:1,proxy_cache:1,proxy_cache_key:1,proxy_cache_methods:1,proxy_cache_min_uses:1,proxy_cache_path:1,proxy_cache_use_stale:1,proxy_cache_valid:1,proxy_connect_timeout:1,proxy_headers_hash_bucket_size:1,proxy_headers_hash_max_size:1,proxy_hide_header:1,proxy_ignore_client_abort:1,proxy_ignore_headers:1,proxy_intercept_errors:1,proxy_max_temp_file_size:1,proxy_method:1,proxy_next_upstream:1,proxy_pass:1,proxy_pass_header:1,proxy_pass_request_body:1,proxy_pass_request_headers:1,
proxy_read_timeout:1,proxy_redirect:1,proxy_send_lowat:1,proxy_send_timeout:1,proxy_set_body:1,proxy_set_header:1,proxy_store:1,proxy_store_access:1,proxy_temp_file_write_size:1,proxy_temp_path:1,proxy_upstream_fail_timeout:1,proxy_upstream_max_fails:1,push_authorized_channels_only:1,push_channel_group:1,push_max_channel_id_length:1,push_max_channel_subscribers:1,push_max_message_buffer_length:1,push_max_reserved_memory:1,push_message_buffer_length:1,push_message_timeout:1,push_min_message_buffer_length:1,
push_min_message_recipients:1,push_publisher:1,push_store_messages:1,push_subscriber:1,push_subscriber_concurrency:1,random_index:1,read_ahead:1,real_ip_header:1,recursive_error_pages:1,request_pool_size:1,reset_timedout_connection:1,resolver:1,resolver_timeout:1,"return":1,rewrite:1,rewrite_log:1,root:1,satisfy:1,satisfy_any:1,send_lowat:1,send_timeout:1,sendfile:1,sendfile_max_chunk:1,server:1,server:1,server_name:1,server_name_in_redirect:1,server_names_hash_bucket_size:1,server_names_hash_max_size:1,
server_tokens:1,set:1,set_real_ip_from:1,source_charset:1,source_charset:1,ssi:1,ssi_ignore_recycled_buffers:1,ssi_min_file_chunk:1,ssi_silent_errors:1,ssi_types:1,ssi_value_length:1,ssl:1,ssl_certificate:1,ssl_certificate_key:1,ssl_ciphers:1,ssl_client_certificate:1,ssl_crl:1,ssl_dhparam:1,ssl_prefer_server_ciphers:1,ssl_protocols:1,ssl_session_cache:1,ssl_session_timeout:1,ssl_verify_client:1,ssl_verify_depth:1,sub_filter:1,sub_filter_once:1,sub_filter_types:1,tcp_nodelay:1,tcp_nopush:1,timer_resolution:1,
try_files:1,types:1,types_hash_bucket_size:1,types_hash_max_size:1,underscores_in_headers:1,uninitialized_variable_warn:1,upstream:1,use:1,user:1,userid:1,userid:1,userid_domain:1,userid_domain:1,userid_expires:1,userid_expires:1,userid_mark:1,userid_name:1,userid_name:1,userid_p3p:1,userid_p3p:1,userid_path:1,userid_path:1,userid_service:1,userid_service:1,valid_referers:1,variables_hash_bucket_size:1,variables_hash_max_size:1,worker_connections:1,worker_cpu_affinity:1,worker_priority:1,worker_processes:1,
worker_rlimit_core:1,worker_rlimit_nofile:1,worker_rlimit_sigpending:1,working_directory:1,xml_entities:1,xslt_stylesheet:1,xslt_types:1},relevance:0,contains:[hljs.HASH_COMMENT_MODE,{begin:"\\s",end:"[;{]",returnBegin:!0,returnEnd:!0,lexems:"[a-z/]+",keywords:{built_in:{on:1,off:1,yes:1,no:1,"true":1,"false":1,none:1,blocked:1,debug:1,info:1,notice:1,warn:1,error:1,crit:1,select:1,permanent:1,redirect:1,kqueue:1,rtsig:1,epoll:1,poll:1,"/dev/poll":1}},relevance:0,contains:[hljs.HASH_COMMENT_MODE,
{className:"string",begin:'"',end:'"',contains:[hljs.BACKSLASH_ESCAPE,c,a,b],relevance:0},{className:"string",begin:"'",end:"'",contains:[hljs.BACKSLASH_ESCAPE,c,a,b],relevance:0},{className:"string",begin:"([a-z]+):/",end:"[;\\s]",returnEnd:!0},{className:"regexp",begin:"\\s\\^",end:"\\s|{|;",returnEnd:!0,contains:[hljs.BACKSLASH_ESCAPE,c,a,b]},{className:"regexp",begin:"~\\*?\\s+",end:"\\s|{|;",returnEnd:!0,contains:[hljs.BACKSLASH_ESCAPE,c,a,b]},{className:"regexp",begin:"\\*(\\.[a-z\\-]+)+",contains:[hljs.BACKSLASH_ESCAPE,
c,a,b]},{className:"regexp",begin:"([a-z\\-]+\\.)+\\*",contains:[hljs.BACKSLASH_ESCAPE,c,a,b]},{className:"number",begin:"\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b"},{className:"number",begin:"\\s\\d+[kKmMgGdshdwy]*\\b",relevance:0},c,a,b]}]}]}}}();
hljs.LANGUAGES.objectivec=function(){return{defaultMode:{keywords:{keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,sizeof:2,typedef:2,"const":1,struct:1,"for":1,union:1,unsigned:1,"long":1,"volatile":2,"static":1,"protected":1,bool:1,mutable:1,"if":1,"public":1,"do":1,"return":1,"goto":1,"void":2,"enum":1,"else":1,"break":1,extern:1,"true":1,"class":1,asm:1,"case":1,"short":1,"default":1,"double":1,"throw":1,register:1,explicit:1,signed:1,typename:1,"try":1,
"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,readonly:1,assign:1,property:1,protocol:10,self:1,"synchronized":1,end:1,synthesize:50,id:1,optional:1,required:1,implementation:10,nonatomic:1,"interface":1,"super":1,unichar:1,"finally":2,dynamic:2,nil:1},built_in:{YES:5,NO:5,NULL:1,IBOutlet:50,IBAction:50,NSString:50,NSDictionary:50,CGRect:50,CGPoint:50,NSRange:50,release:1,retain:1,autorelease:50,UIButton:50,UILabel:50,UITextView:50,UIWebView:50,MKMapView:50,UISegmentedControl:50,NSObject:50,
UITableViewDelegate:50,UITableViewDataSource:50,NSThread:50,UIActivityIndicator:50,UITabbar:50,UIToolBar:50,UIBarButtonItem:50,UIImageView:50,NSAutoreleasePool:50,UITableView:50,BOOL:1,NSInteger:20,CGFloat:20,NSException:50,NSLog:50,NSMutableString:50,NSMutableArray:50,NSMutableDictionary:50,NSURL:50}},illegal:"</",contains:[hljs.C_LINE_COMMENT_MODE,hljs.C_BLOCK_COMMENT_MODE,hljs.C_NUMBER_MODE,hljs.QUOTE_STRING_MODE,{className:"string",begin:"'",end:"[^\\\\]'",illegal:"[^\\\\][^']"},{className:"preprocessor",
begin:"#import",end:"$",contains:[{className:"title",begin:'"',end:'"'},{className:"title",begin:"<",end:">"}]},{className:"preprocessor",begin:"#",end:"$"},{className:"class",begin:"interface|class|protocol|implementation",end:"({|$)",keywords:{"interface":1,"class":1,protocol:5,implementation:5},contains:[{className:"id",begin:hljs.UNDERSCORE_IDENT_RE}]}]}}}();
hljs.LANGUAGES.perl=function(){var c={getpwent:1,getservent:1,quotemeta:1,msgrcv:1,scalar:1,kill:1,dbmclose:1,undef:1,lc:1,ma:1,syswrite:1,tr:1,send:1,umask:1,sysopen:1,shmwrite:1,vec:1,qx:1,utime:1,local:1,oct:1,semctl:1,localtime:1,readpipe:1,"do":1,"return":1,format:1,read:1,sprintf:1,dbmopen:1,pop:1,getpgrp:1,not:1,getpwnam:1,rewinddir:1,qq:1,fileno:1,qw:1,endprotoent:1,wait:1,sethostent:1,bless:1,s:1,opendir:1,"continue":1,each:1,sleep:1,endgrent:1,shutdown:1,dump:1,chomp:1,connect:1,getsockname:1,
die:1,socketpair:1,close:1,flock:1,exists:1,index:1,shmget:1,sub:1,"for":1,endpwent:1,redo:1,lstat:1,msgctl:1,setpgrp:1,abs:1,exit:1,select:1,print:1,ref:1,gethostbyaddr:1,unshift:1,fcntl:1,syscall:1,"goto":1,getnetbyaddr:1,join:1,gmtime:1,symlink:1,semget:1,splice:1,x:1,getpeername:1,recv:1,log:1,setsockopt:1,cos:1,last:1,reverse:1,gethostbyname:1,getgrnam:1,study:1,formline:1,endhostent:1,times:1,chop:1,length:1,gethostent:1,getnetent:1,pack:1,getprotoent:1,getservbyname:1,rand:1,mkdir:1,pos:1,
chmod:1,y:1,substr:1,endnetent:1,printf:1,next:1,open:1,msgsnd:1,readdir:1,use:1,unlink:1,getsockopt:1,getpriority:1,rindex:1,wantarray:1,hex:1,system:1,getservbyport:1,endservent:1,"int":1,chr:1,untie:1,rmdir:1,prototype:1,tell:1,listen:1,fork:1,shmread:1,ucfirst:1,setprotoent:1,"else":1,sysseek:1,link:1,getgrgid:1,shmctl:1,waitpid:1,unpack:1,getnetbyname:1,reset:1,chdir:1,grep:1,split:1,require:1,caller:1,lcfirst:1,until:1,warn:1,"while":1,values:1,shift:1,telldir:1,getpwuid:1,my:1,getprotobynumber:1,
"delete":1,and:1,sort:1,uc:1,defined:1,srand:1,accept:1,"package":1,seekdir:1,getprotobyname:1,semop:1,our:1,rename:1,seek:1,"if":1,q:1,chroot:1,sysread:1,setpwent:1,no:1,crypt:1,getc:1,chown:1,sqrt:1,write:1,setnetent:1,setpriority:1,foreach:1,tie:1,sin:1,msgget:1,map:1,stat:1,getlogin:1,unless:1,elsif:1,truncate:1,exec:1,keys:1,glob:1,tied:1,closedir:1,ioctl:1,socket:1,readlink:1,eval:1,xor:1,readline:1,binmode:1,setservent:1,eof:1,ord:1,bind:1,alarm:1,pipe:1,atan2:1,getgrent:1,exp:1,time:1,push:1,
setgrent:1,gt:1,lt:1,or:1,ne:1,m:1},a={className:"subst",begin:"[$@]\\{",end:"}",keywords:c,relevance:10},b={className:"variable",begin:"\\$\\d"},k={className:"variable",begin:"[\\$\\%\\@\\*](\\^\\w\\b|#\\w+(\\:\\:\\w+)*|[^\\s\\w{]|{\\w+}|\\w+(\\:\\:\\w*)*)"},g=[hljs.BACKSLASH_ESCAPE,a,b,k],f={begin:"->",contains:[{begin:hljs.IDENT_RE},{begin:"{",end:"}"}]},b=[b,k,hljs.HASH_COMMENT_MODE,{className:"comment",begin:"^(__END__|__DATA__)",end:"\\n$",relevance:5},f,{className:"string",begin:"q[qwxr]?\\s*\\(",
end:"\\)",contains:g,relevance:5},{className:"string",begin:"q[qwxr]?\\s*\\[",end:"\\]",contains:g,relevance:5},{className:"string",begin:"q[qwxr]?\\s*\\{",end:"\\}",contains:g,relevance:5},{className:"string",begin:"q[qwxr]?\\s*\\|",end:"\\|",contains:g,relevance:5},{className:"string",begin:"q[qwxr]?\\s*\\<",end:"\\>",contains:g,relevance:5},{className:"string",begin:"qw\\s+q",end:"q",contains:g,relevance:5},{className:"string",begin:"'",end:"'",contains:[hljs.BACKSLASH_ESCAPE],relevance:0},{className:"string",
begin:'"',end:'"',contains:g,relevance:0},{className:"string",begin:"`",end:"`",contains:[hljs.BACKSLASH_ESCAPE]},{className:"string",begin:"{\\w+}",relevance:0},{className:"string",begin:"-?\\w+\\s*\\=\\>",relevance:0},{className:"number",begin:"(\\b0[0-7_]+)|(\\b0x[0-9a-fA-F_]+)|(\\b[1-9][0-9_]*(\\.[0-9_]+)?)|[0_]\\b",relevance:0},{className:"regexp",begin:"(s|tr|y)/(\\\\.|[^/])*/(\\\\.|[^/])*/[a-z]*",relevance:10},{className:"regexp",begin:"(m|qr)?/",end:"/[a-z]*",contains:[hljs.BACKSLASH_ESCAPE],
relevance:0},{className:"sub",begin:"\\bsub\\b",end:"(\\s*\\(.*?\\))?[;{]",keywords:{sub:1},relevance:5},{className:"operator",begin:"-\\w\\b",relevance:0},{className:"pod",begin:"\\=\\w",end:"\\=cut"}];a.contains=b;f.contains[1].contains=b;return{defaultMode:{keywords:c,contains:b}}}();
hljs.LANGUAGES.php={case_insensitive:!0,defaultMode:{keywords:{and:1,include_once:1,list:1,"abstract":1,global:1,"private":1,echo:1,"interface":1,as:1,"static":1,endswitch:1,array:1,"null":1,"if":1,endwhile:1,or:1,"const":1,"for":1,endforeach:1,self:1,"var":1,"while":1,isset:1,"public":1,"protected":1,exit:1,foreach:1,"throw":1,elseif:1,"extends":1,include:1,__FILE__:1,empty:1,require_once:1,"function":1,"do":1,xor:1,"return":1,"implements":1,parent:1,clone:1,use:1,__CLASS__:1,__LINE__:1,"else":1,
"break":1,print:1,eval:1,"new":1,"catch":1,__METHOD__:1,"class":1,"case":1,exception:1,php_user_filter:1,"default":1,die:1,require:1,__FUNCTION__:1,enddeclare:1,"final":1,"try":1,"this":1,"switch":1,"continue":1,endfor:1,endif:1,declare:1,unset:1,"true":1,"false":1,namespace:1},contains:[hljs.C_LINE_COMMENT_MODE,hljs.HASH_COMMENT_MODE,{className:"comment",begin:"/\\*",end:"\\*/",contains:[{className:"phpdoc",begin:"\\s@[A-Za-z]+",relevance:10}]},hljs.C_NUMBER_MODE,hljs.inherit(hljs.APOS_STRING_MODE,
{illegal:null}),hljs.inherit(hljs.QUOTE_STRING_MODE,{illegal:null}),{className:"variable",begin:"\\$[a-zA-Z_\u007f-\u00ff][a-zA-Z0-9_\u007f-\u00ff]*"},{className:"preprocessor",begin:"<\\?php",relevance:10},{className:"preprocessor",begin:"\\?>"}]}};
hljs.LANGUAGES.profile={defaultMode:{contains:[hljs.C_NUMBER_MODE,{className:"builtin",begin:"{",end:"}$",excludeBegin:!0,excludeEnd:!0,contains:[hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE],relevance:0},{className:"filename",begin:"(/w|[a-zA-Z_][da-zA-Z_]+\\.[da-zA-Z_]{1,3})",end:":",excludeEnd:!0},{className:"header",begin:"(ncalls|tottime|cumtime)",end:"$",keywords:{ncalls:1,tottime:10,cumtime:10,filename:1},relevance:10},{className:"summary",begin:"function calls",end:"$",contains:[hljs.C_NUMBER_MODE],
relevance:10},hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,{className:"function",begin:"\\(",end:"\\)$",contains:[{className:"title",begin:hljs.UNDERSCORE_IDENT_RE,relevance:0}],relevance:0}]}};
hljs.LANGUAGES.python=function(){var c={className:"string",begin:"(u|b)?r?'''",end:"'''",relevance:10},a={className:"string",begin:'(u|b)?r?"""',end:'"""',relevance:10},b={className:"string",begin:"(u|r|ur|b|br)'",end:"'",contains:[hljs.BACKSLASH_ESCAPE],relevance:10},k={className:"string",begin:'(u|r|ur|b|br)"',end:'"',contains:[hljs.BACKSLASH_ESCAPE],relevance:10},g={className:"title",begin:hljs.UNDERSCORE_IDENT_RE},f={className:"params",begin:"\\(",end:"\\)",contains:[c,a,b,k,hljs.APOS_STRING_MODE,
hljs.QUOTE_STRING_MODE]};return{defaultMode:{keywords:{keyword:{and:1,elif:1,is:1,global:1,as:1,"in":1,"if":1,from:1,raise:1,"for":1,except:1,"finally":1,print:1,"import":1,pass:1,"return":1,exec:1,"else":1,"break":1,not:1,"with":1,"class":1,assert:1,yield:1,"try":1,"while":1,"continue":1,del:1,or:1,def:1,lambda:1,nonlocal:10},built_in:{None:1,True:1,False:1,Ellipsis:1,NotImplemented:1}},illegal:"(</|->|\\?)",contains:[hljs.HASH_COMMENT_MODE,c,a,b,k,hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,{className:"function",
begin:"\\bdef ",end:":",illegal:"$",keywords:{def:1},contains:[g,f],relevance:10},{className:"class",begin:"\\bclass ",end:":",illegal:"[${]",keywords:{"class":1},contains:[g,f],relevance:10},hljs.C_NUMBER_MODE,{className:"decorator",begin:"@",end:"$"}]}}}();
hljs.LANGUAGES.ruby=function(){var c={keyword:{and:1,"false":1,then:1,defined:1,module:1,"in":1,"return":1,redo:1,"if":1,BEGIN:1,retry:1,end:1,"for":1,"true":1,self:1,when:1,next:1,until:1,"do":1,begin:1,unless:1,END:1,rescue:1,nil:1,"else":1,"break":1,undef:1,not:1,"super":1,"class":1,"case":1,require:1,yield:1,alias:1,"while":1,ensure:1,elsif:1,or:1,def:1},keymethods:{__id__:1,__send__:1,abort:1,abs:1,"all?":1,allocate:1,ancestors:1,"any?":1,arity:1,assoc:1,at:1,at_exit:1,autoload:1,"autoload?":1,
"between?":1,binding:1,binmode:1,"block_given?":1,call:1,callcc:1,caller:1,capitalize:1,"capitalize!":1,casecmp:1,"catch":1,ceil:1,center:1,chomp:1,"chomp!":1,chop:1,"chop!":1,chr:1,"class":1,class_eval:1,"class_variable_defined?":1,class_variables:1,clear:1,clone:1,close:1,close_read:1,close_write:1,"closed?":1,coerce:1,collect:1,"collect!":1,compact:1,"compact!":1,concat:1,"const_defined?":1,const_get:1,const_missing:1,const_set:1,constants:1,count:1,crypt:1,"default":1,default_proc:1,"delete":1,
"delete!":1,delete_at:1,delete_if:1,detect:1,display:1,div:1,divmod:1,downcase:1,"downcase!":1,downto:1,dump:1,dup:1,each:1,each_byte:1,each_index:1,each_key:1,each_line:1,each_pair:1,each_value:1,each_with_index:1,"empty?":1,entries:1,eof:1,"eof?":1,"eql?":1,"equal?":1,eval:1,exec:1,exit:1,"exit!":1,extend:1,fail:1,fcntl:1,fetch:1,fileno:1,fill:1,find:1,find_all:1,first:1,flatten:1,"flatten!":1,floor:1,flush:1,for_fd:1,foreach:1,fork:1,format:1,freeze:1,"frozen?":1,fsync:1,getc:1,gets:1,global_variables:1,
grep:1,gsub:1,"gsub!":1,"has_key?":1,"has_value?":1,hash:1,hex:1,id:1,include:1,"include?":1,included_modules:1,index:1,indexes:1,indices:1,induced_from:1,inject:1,insert:1,inspect:1,instance_eval:1,instance_method:1,instance_methods:1,"instance_of?":1,"instance_variable_defined?":1,instance_variable_get:1,instance_variable_set:1,instance_variables:1,"integer?":1,intern:1,invert:1,ioctl:1,"is_a?":1,isatty:1,"iterator?":1,join:1,"key?":1,keys:1,"kind_of?":1,lambda:1,last:1,length:1,lineno:1,ljust:1,
load:1,local_variables:1,loop:1,lstrip:1,"lstrip!":1,map:1,"map!":1,match:1,max:1,"member?":1,merge:1,"merge!":1,method:1,"method_defined?":1,method_missing:1,methods:1,min:1,module_eval:1,modulo:1,name:1,nesting:1,"new":1,next:1,"next!":1,"nil?":1,nitems:1,"nonzero?":1,object_id:1,oct:1,open:1,pack:1,partition:1,pid:1,pipe:1,pop:1,popen:1,pos:1,prec:1,prec_f:1,prec_i:1,print:1,printf:1,private_class_method:1,private_instance_methods:1,"private_method_defined?":1,private_methods:1,proc:1,protected_instance_methods:1,
"protected_method_defined?":1,protected_methods:1,public_class_method:1,public_instance_methods:1,"public_method_defined?":1,public_methods:1,push:1,putc:1,puts:1,quo:1,raise:1,rand:1,rassoc:1,read:1,read_nonblock:1,readchar:1,readline:1,readlines:1,readpartial:1,rehash:1,reject:1,"reject!":1,remainder:1,reopen:1,replace:1,require:1,"respond_to?":1,reverse:1,"reverse!":1,reverse_each:1,rewind:1,rindex:1,rjust:1,round:1,rstrip:1,"rstrip!":1,scan:1,seek:1,select:1,send:1,set_trace_func:1,shift:1,singleton_method_added:1,
singleton_methods:1,size:1,sleep:1,slice:1,"slice!":1,sort:1,"sort!":1,sort_by:1,split:1,sprintf:1,squeeze:1,"squeeze!":1,srand:1,stat:1,step:1,store:1,strip:1,"strip!":1,sub:1,"sub!":1,succ:1,"succ!":1,sum:1,superclass:1,swapcase:1,"swapcase!":1,sync:1,syscall:1,sysopen:1,sysread:1,sysseek:1,system:1,syswrite:1,taint:1,"tainted?":1,tell:1,test:1,"throw":1,times:1,to_a:1,to_ary:1,to_f:1,to_hash:1,to_i:1,to_int:1,to_io:1,to_proc:1,to_s:1,to_str:1,to_sym:1,tr:1,"tr!":1,tr_s:1,"tr_s!":1,trace_var:1,
transpose:1,trap:1,truncate:1,"tty?":1,type:1,ungetc:1,uniq:1,"uniq!":1,unpack:1,unshift:1,untaint:1,untrace_var:1,upcase:1,"upcase!":1,update:1,upto:1,"value?":1,values:1,values_at:1,warn:1,write:1,write_nonblock:1,"zero?":1,zip:1}},a={className:"yardoctag",begin:"@[A-Za-z]+"},b={className:"comment",begin:"#",end:"$",contains:[a]},k={className:"comment",begin:"^\\=begin",end:"^\\=end",contains:[a],relevance:10},g={className:"comment",begin:"^__END__",end:"\\n$"},a={className:"subst",begin:"#\\{",
end:"}",lexems:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",keywords:c},f=[hljs.BACKSLASH_ESCAPE,a],s={className:"string",begin:"'",end:"'",contains:f,relevance:0},q={className:"string",begin:'"',end:'"',contains:f,relevance:0},r={className:"string",begin:"%[qw]?\\(",end:"\\)",contains:f,relevance:10},n={className:"string",begin:"%[qw]?\\[",end:"\\]",contains:f,relevance:10},j={className:"string",begin:"%[qw]?{",end:"}",contains:f,relevance:10},p={className:"string",begin:"%[qw]?<",end:">",contains:f,relevance:10},
t={className:"string",begin:"%[qw]?/",end:"/",contains:f,relevance:10},i={className:"string",begin:"%[qw]?%",end:"%",contains:f,relevance:10},d={className:"string",begin:"%[qw]?-",end:"-",contains:f,relevance:10},m={className:"string",begin:"%[qw]?\\|",end:"\\|",contains:f,relevance:10},f={className:"function",begin:"\\bdef\\s+",end:" |$|;",lexems:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",keywords:c,contains:[{className:"title",begin:"[a-zA-Z_]\\w*[!?=]?|[-+~]\\@|<<|>>|=~|===?|<=>|[<>]=?|\\*\\*|[-/+%^&*~`|]|\\[\\]=?",
lexems:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",keywords:c},{className:"params",begin:"\\(",end:"\\)",lexems:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",keywords:c},b,k,g]},e={className:"identifier",begin:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",lexems:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",keywords:c,relevance:0},b=[b,k,g,s,q,r,n,j,p,t,i,d,m,{className:"class",begin:"\\b(class|module)\\b",end:"$|;",keywords:{"class":1,module:1},contains:[{className:"title",begin:"[A-Za-z_]\\w*(::\\w+)*(\\?|\\!)?",relevance:0},{className:"inheritance",
begin:"<\\s*",contains:[{className:"parent",begin:"("+hljs.IDENT_RE+"::)?"+hljs.IDENT_RE}]},b,k,g]},f,{className:"constant",begin:"(::)?([A-Z]\\w*(::)?)+",relevance:0},{className:"symbol",begin:":",contains:[s,q,r,n,j,p,t,i,d,m,e],relevance:0},{className:"number",begin:"(\\b0[0-7_]+)|(\\b0x[0-9a-fA-F_]+)|(\\b[1-9][0-9_]*(\\.[0-9_]+)?)|[0_]\\b",relevance:0},{className:"number",begin:"\\?\\w"},{className:"variable",begin:"(\\$\\W)|((\\$|\\@\\@?)(\\w+))"},e,{begin:"("+hljs.RE_STARTERS_RE+")\\s*",contains:[b,
k,g,{className:"regexp",begin:"/",end:"/[a-z]*",illegal:"\\n",contains:[hljs.BACKSLASH_ESCAPE]}],relevance:0}];a.contains=b;f.contains[1].contains=b;return{defaultMode:{lexems:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",keywords:c,contains:b}}}();
hljs.LANGUAGES.scala=function(){var c={className:"annotation",begin:"@[A-Za-z]+"},a={className:"string",begin:'u?r?"""',end:'"""',relevance:10};return{defaultMode:{keywords:{type:1,yield:1,lazy:1,override:1,def:1,"with":1,val:1,"var":1,"false":1,"true":1,sealed:1,"abstract":1,"private":1,trait:1,object:1,"null":1,"if":1,"for":1,"while":1,"throw":1,"finally":1,"protected":1,"extends":1,"import":1,"final":1,"return":1,"else":1,"break":1,"new":1,"catch":1,"super":1,"class":1,"case":1,"package":1,"default":1,
"try":1,"this":1,match:1,"continue":1,"throws":1},contains:[{className:"javadoc",begin:"/\\*\\*",end:"\\*/",contains:[{className:"javadoctag",begin:"@[A-Za-z]+"}],relevance:10},hljs.C_LINE_COMMENT_MODE,hljs.C_BLOCK_COMMENT_MODE,hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,a,{className:"class",begin:"((case )?class |object |trait )",end:"({|$)",illegal:":",keywords:{"case":1,"class":1,trait:1,object:1},contains:[{begin:"(extends|with)",keywords:{"extends":1,"with":1},relevance:10},{className:"title",
begin:hljs.UNDERSCORE_IDENT_RE},{className:"params",begin:"\\(",end:"\\)",contains:[hljs.APOS_STRING_MODE,hljs.QUOTE_STRING_MODE,a,c]}]},hljs.C_NUMBER_MODE,c]}}}();
hljs.LANGUAGES.sql={case_insensitive:!0,defaultMode:{illegal:"[^\\s]",contains:[{className:"operator",begin:"(begin|start|commit|rollback|savepoint|lock|alter|create|drop|rename|call|delete|do|handler|insert|load|replace|select|truncate|update|set|show|pragma|grant)\\b",end:";|$",keywords:{keyword:{all:1,partial:1,global:1,month:1,current_timestamp:1,using:1,go:1,revoke:1,smallint:1,indicator:1,"end-exec":1,disconnect:1,zone:1,"with":1,character:1,assertion:1,to:1,add:1,current_user:1,usage:1,input:1,
local:1,alter:1,match:1,collate:1,real:1,then:1,rollback:1,get:1,read:1,timestamp:1,session_user:1,not:1,integer:1,bit:1,unique:1,day:1,minute:1,desc:1,insert:1,execute:1,like:1,ilike:2,level:1,decimal:1,drop:1,"continue":1,isolation:1,found:1,where:1,constraints:1,domain:1,right:1,national:1,some:1,module:1,transaction:1,relative:1,second:1,connect:1,escape:1,close:1,system_user:1,"for":1,deferred:1,section:1,cast:1,current:1,sqlstate:1,allocate:1,intersect:1,deallocate:1,numeric:1,"public":1,preserve:1,
full:1,"goto":1,initially:1,asc:1,no:1,key:1,output:1,collation:1,group:1,by:1,union:1,session:1,both:1,last:1,language:1,constraint:1,column:1,of:1,space:1,foreign:1,deferrable:1,prior:1,connection:1,unknown:1,action:1,commit:1,view:1,or:1,first:1,into:1,"float":1,year:1,primary:1,cascaded:1,except:1,restrict:1,set:1,references:1,names:1,table:1,outer:1,open:1,select:1,size:1,are:1,rows:1,from:1,prepare:1,distinct:1,leading:1,create:1,only:1,next:1,inner:1,authorization:1,schema:1,corresponding:1,
option:1,declare:1,precision:1,immediate:1,"else":1,timezone_minute:1,external:1,varying:1,translation:1,"true":1,"case":1,exception:1,join:1,hour:1,"default":1,"double":1,scroll:1,value:1,cursor:1,descriptor:1,values:1,dec:1,fetch:1,procedure:1,"delete":1,and:1,"false":1,"int":1,is:1,describe:1,"char":1,as:1,at:1,"in":1,varchar:1,"null":1,trailing:1,any:1,absolute:1,current_time:1,end:1,grant:1,privileges:1,when:1,cross:1,check:1,write:1,current_date:1,pad:1,begin:1,temporary:1,exec:1,time:1,update:1,
catalog:1,user:1,sql:1,date:1,on:1,identity:1,timezone_hour:1,natural:1,whenever:1,interval:1,work:1,order:1,cascade:1,diagnostics:1,nchar:1,having:1,left:1,call:1,"do":1,handler:1,load:1,replace:1,truncate:1,start:1,lock:1,show:1,pragma:1},aggregate:{count:1,sum:1,min:1,max:1,avg:1}},contains:[{className:"string",begin:"'",end:"'",contains:[hljs.BACKSLASH_ESCAPE,{begin:"''"}],relevance:0},{className:"string",begin:'"',end:'"',contains:[hljs.BACKSLASH_ESCAPE,{begin:'""'}],relevance:0},{className:"string",
begin:"`",end:"`",contains:[hljs.BACKSLASH_ESCAPE]},hljs.C_NUMBER_MODE,{begin:"\\n"}]},hljs.C_BLOCK_COMMENT_MODE,{className:"comment",begin:"--",end:"$"}]}};
hljs.LANGUAGES.tex=function(){var c={className:"command",begin:"\\\\[a-zA-Z\u0430-\u044f\u0410-\u044f]+[\\*]?",relevance:10},a={className:"command",begin:"\\\\[^a-zA-Z\u0430-\u044f\u0410-\u044f0-9]",relevance:0},b={className:"special",begin:"[{}\\[\\]\\&#~]",relevance:0};return{defaultMode:{contains:[{begin:"\\\\[a-zA-Z\u0430-\u044f\u0410-\u044f]+[\\*]? *= *-?\\d*\\.?\\d+(pt|pc|mm|cm|in|dd|cc|ex|em)?",returnBegin:!0,contains:[c,a,{className:"number",begin:" *=",end:"-?\\d*\\.?\\d+(pt|pc|mm|cm|in|dd|cc|ex|em)?",
excludeBegin:!0}],relevance:10},c,a,b,{className:"formula",begin:"\\$\\$",end:"\\$\\$",contains:[c,a,b],relevance:0},{className:"formula",begin:"\\$",end:"\\$",contains:[c,a,b],relevance:0},{className:"comment",begin:"%",end:"$",relevance:0}]}}}();
hljs.LANGUAGES.vbscript={case_insensitive:!0,defaultMode:{keywords:{keyword:{call:1,"class":1,"const":1,dim:1,"do":1,loop:1,erase:1,execute:1,executeglobal:1,exit:1,"for":1,each:1,next:1,"function":1,"if":1,then:1,"else":1,on:1,error:1,option:1,explicit:1,"new":1,"private":1,property:1,let:1,get:1,"public":1,randomize:1,redim:1,rem:1,select:1,"case":1,set:1,stop:1,sub:1,"while":1,wend:1,"with":1,end:1,to:1,elseif:1,is:1,or:1,xor:1,and:1,not:1,class_initialize:1,class_terminate:1,"default":1,preserve:1,
"in":1,me:1,byval:1,byref:1,step:1,resume:1,"goto":1},built_in:{lcase:1,month:1,vartype:1,instrrev:1,ubound:1,setlocale:1,getobject:1,rgb:1,getref:1,string:1,weekdayname:1,rnd:1,dateadd:1,monthname:1,now:1,day:1,minute:1,isarray:1,cbool:1,round:1,formatcurrency:1,conversions:1,csng:1,timevalue:1,second:1,year:1,space:1,abs:1,clng:1,timeserial:1,fixs:1,len:1,asc:1,isempty:1,maths:1,dateserial:1,atn:1,timer:1,isobject:1,filter:1,weekday:1,datevalue:1,ccur:1,isdate:1,instr:1,datediff:1,formatdatetime:1,
replace:1,isnull:1,right:1,sgn:1,array:1,snumeric:1,log:1,cdbl:1,hex:1,chr:1,lbound:1,msgbox:1,ucase:1,getlocale:1,cos:1,cdate:1,cbyte:1,rtrim:1,join:1,hour:1,oct:1,typename:1,trim:1,strcomp:1,"int":1,createobject:1,loadpicture:1,tan:1,formatnumber:1,mid:1,scriptenginebuildversion:1,scriptengine:1,split:1,scriptengineminorversion:1,cint:1,sin:1,datepart:1,ltrim:1,sqr:1,scriptenginemajorversion:1,time:1,derived:1,eval:1,date:1,formatpercent:1,exp:1,inputbox:1,left:1,ascw:1,chrw:1,regexp:1,server:1,
response:1,request:1,cstr:1,err:1},literal:{"true":1,"false":1,"null":1,nothing:1,empty:1}},illegal:"//",contains:[{className:"string",begin:'"',end:'"',illegal:"\\n",contains:[{begin:'""'}],relevance:0},{className:"comment",begin:"'",end:"$"},hljs.C_NUMBER_MODE]}};
hljs.LANGUAGES.xml=function(){var c={endsWithParent:!0,contains:[{className:"attribute",begin:"[A-Za-z0-9\\._:-]+",relevance:0},{begin:'="',returnBegin:!0,end:'"',contains:[{className:"value",begin:'"',endsWithParent:!0}]},{begin:"='",returnBegin:!0,end:"'",contains:[{className:"value",begin:"'",endsWithParent:!0}]},{begin:"=",contains:[{className:"value",begin:"[^\\s/>]+"}]}]};return{case_insensitive:!0,defaultMode:{contains:[{className:"pi",begin:"<\\?",end:"\\?>",relevance:10},{className:"doctype",
begin:"<!DOCTYPE",end:">",relevance:10,contains:[{begin:"\\[",end:"\\]"}]},{className:"comment",begin:"<\!--",end:"--\>",relevance:10},{className:"cdata",begin:"<\\!\\[CDATA\\[",end:"\\]\\]>",relevance:10},{className:"tag",begin:"<style(?=\\s|>|$)",end:">",keywords:{title:{style:1}},contains:[c],starts:{className:"css",end:"</style>",returnEnd:!0,subLanguage:"css"}},{className:"tag",begin:"<script(?=\\s|>|$)",end:">",keywords:{title:{script:1}},contains:[c],starts:{className:"javascript",end:"<\/script>",
returnEnd:!0,subLanguage:"javascript"}},{className:"vbscript",begin:"<%",end:"%>",subLanguage:"vbscript"},{className:"tag",begin:"</?",end:"/?>",contains:[{className:"title",begin:"[^ />]+"},c]}]}}}();
