/*! Socket.IO.js build:0.9.0, development. Copyright(c) 2011 LearnBoost <dev@learnboost.com> MIT Licensed */
(function(h,e){h.version="0.9.0";h.protocol=1;h.transports=[];h.j=[];h.sockets={};h.connect=function(d,a){var g=h.util.parseUri(d),c,b;e&&e.location&&(g.protocol=g.protocol||e.location.protocol.slice(0,-1),g.host=g.host||(e.document?e.document.domain:e.location.hostname),g.port=g.port||e.location.port);c=h.util.uniqueUri(g);var f={host:g.host,secure:"https"==g.protocol,port:g.port||("https"==g.protocol?443:80),query:g.query||""};h.util.merge(f,a);if(f["force new connection"]||!h.sockets[c])b=new h.Socket(f);
!f["force new connection"]&&b&&(h.sockets[c]=b);b=b||h.sockets[c];return b.of(1<g.path.length?g.path:"")}})("object"===typeof module?module.exports:this.io={},this);
(function(h,e){var d=h.util={},a=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,g="source,protocol,authority,userInfo,user,password,host,port,relative,path,directory,file,query,anchor".split(",");d.parseUri=function(b){for(var b=a.exec(b||""),f={},c=14;c--;)f[g[c]]=b[c]||"";return f};d.uniqueUri=function(b){var f=b.protocol,c=b.host,b=b.port;"document"in
e?(c=c||document.domain,b=b||("https"==f&&"https:"!==document.location.protocol?443:document.location.port)):(c=c||"localhost",!b&&"https"==f&&(b=443));return(f||"http")+"://"+c+":"+(b||80)};d.query=function(b,f){var c=d.chunkQuery(b||""),g=[];d.merge(c,d.chunkQuery(f||""));for(var a in c)c.hasOwnProperty(a)&&g.push(a+"="+c[a]);return g.length?"?"+g.join("&"):""};d.chunkQuery=function(b){for(var f={},b=b.split("&"),c=0,g=b.length,a;c<g;++c)a=b[c].split("="),a[0]&&(f[a[0]]=a[1]);return f};var c=!1;
d.load=function(b){if("document"in e&&"complete"===document.readyState||c)return b();d.on(e,"load",b,!1)};d.on=function(b,c,a,g){b.attachEvent?b.attachEvent("on"+c,a):b.addEventListener&&b.addEventListener(c,a,g)};d.request=function(b){if(b&&"undefined"!=typeof XDomainRequest)return new XDomainRequest;if("undefined"!=typeof XMLHttpRequest&&(!b||d.ua.hasCORS))return new XMLHttpRequest;if(!b)try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}return null};"undefined"!=typeof window&&d.load(function(){c=
!0});d.defer=function(b){if(!d.ua.webkit||"undefined"!=typeof importScripts)return b();d.load(function(){setTimeout(b,100)})};d.merge=function(b,c,a,g){var g=g||[],a="undefined"==typeof a?2:a,e;for(e in c)c.hasOwnProperty(e)&&0>d.indexOf(g,e)&&("object"!==typeof b[e]||!a?(b[e]=c[e],g.push(c[e])):d.merge(b[e],c[e],a-1,g));return b};d.mixin=function(b,c){d.merge(b.prototype,c.prototype)};d.inherit=function(b,c){function a(){}a.prototype=c.prototype;b.prototype=new a};d.isArray=Array.isArray||function(b){return"[object Array]"===
Object.prototype.toString.call(b)};d.intersect=function(b,c){for(var a=[],g=b.length>c.length?b:c,e=b.length>c.length?c:b,j=0,p=e.length;j<p;j++)~d.indexOf(g,e[j])&&a.push(e[j]);return a};d.indexOf=function(b,c,a){for(var g=b.length,a=0>a?0>a+g?0:a+g:a||0;a<g&&b[a]!==c;a++);return g<=a?-1:a};d.toArray=function(b){for(var c=[],a=0,g=b.length;a<g;a++)c.push(b[a]);return c};d.ua={};d.ua.hasCORS="undefined"!=typeof XMLHttpRequest&&function(){try{var b=new XMLHttpRequest}catch(c){return!1}return void 0!=
b.withCredentials}();d.ua.webkit="undefined"!=typeof navigator&&/webkit/i.test(navigator.userAgent)})("undefined"!=typeof io?io:module.exports,this);
(function(h,e){function d(){}h.EventEmitter=d;d.prototype.on=function(a,g){this.$events||(this.$events={});this.$events[a]?e.util.isArray(this.$events[a])?this.$events[a].push(g):this.$events[a]=[this.$events[a],g]:this.$events[a]=g;return this};d.prototype.addListener=d.prototype.on;d.prototype.once=function(a,g){function c(){b.removeListener(a,c);g.apply(this,arguments)}var b=this;c.listener=g;this.on(a,c);return this};d.prototype.removeListener=function(a,g){if(this.$events&&this.$events[a]){var c=
this.$events[a];if(e.util.isArray(c)){for(var b=-1,f=0,d=c.length;f<d;f++)if(c[f]===g||c[f].listener&&c[f].listener===g){b=f;break}if(0>b)return this;c.splice(b,1);c.length||delete this.$events[a]}else(c===g||c.listener&&c.listener===g)&&delete this.$events[a]}return this};d.prototype.removeAllListeners=function(a){this.$events&&this.$events[a]&&(this.$events[a]=null);return this};d.prototype.listeners=function(a){this.$events||(this.$events={});this.$events[a]||(this.$events[a]=[]);e.util.isArray(this.$events[a])||
(this.$events[a]=[this.$events[a]]);return this.$events[a]};d.prototype.emit=function(a){if(!this.$events)return!1;var g=this.$events[a];if(!g)return!1;var c=Array.prototype.slice.call(arguments,1);if("function"==typeof g)g.apply(this,c);else if(e.util.isArray(g))for(var g=g.slice(),b=0,f=g.length;b<f;b++)g[b].apply(this,c);else return!1;return!0}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(h,e){function d(b){return 10>b?"0"+b:b}function a(b){f.lastIndex=0;return f.test(b)?'"'+b.replace(f,function(b){var c=l[b];return"string"===typeof c?c:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function g(b,c){var f,e,l,h,o=i,m,k=c[b];k instanceof Date&&(k=isFinite(b.valueOf())?b.getUTCFullYear()+"-"+d(b.getUTCMonth()+1)+"-"+d(b.getUTCDate())+"T"+d(b.getUTCHours())+":"+d(b.getUTCMinutes())+":"+d(b.getUTCSeconds())+"Z":null);"function"===typeof j&&(k=j.call(c,b,
k));switch(typeof k){case "string":return a(k);case "number":return isFinite(k)?""+k:"null";case "boolean":case "null":return""+k;case "object":if(!k)return"null";i+=n;m=[];if("[object Array]"===Object.prototype.toString.apply(k)){h=k.length;for(f=0;f<h;f+=1)m[f]=g(f,k)||"null";l=0===m.length?"[]":i?"[\n"+i+m.join(",\n"+i)+"\n"+o+"]":"["+m.join(",")+"]";i=o;return l}if(j&&"object"===typeof j){h=j.length;for(f=0;f<h;f+=1)"string"===typeof j[f]&&(e=j[f],(l=g(e,k))&&m.push(a(e)+(i?": ":":")+l))}else for(e in k)Object.prototype.hasOwnProperty.call(k,
e)&&(l=g(e,k))&&m.push(a(e)+(i?": ":":")+l);l=0===m.length?"{}":i?"{\n"+i+m.join(",\n"+i)+"\n"+o+"}":"{"+m.join(",")+"}";i=o;return l}}if(e&&e.parse)return h.JSON={parse:e.parse,stringify:e.stringify};var c=h.JSON={},b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,i,n,l={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f",
"\r":"\\r",'"':'\\"',"\\":"\\\\"},j;c.stringify=function(b,c,a){var f;n=i="";if("number"===typeof a)for(f=0;f<a;f+=1)n+=" ";else"string"===typeof a&&(n=a);if((j=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return g("",{"":b})};c.parse=function(c,a){function g(b,c){var f,d,e=b[c];if(e&&"object"===typeof e)for(f in e)Object.prototype.hasOwnProperty.call(e,f)&&(d=g(e,f),void 0!==d?e[f]=d:delete e[f]);return a.call(b,c,e)}var f,c=""+c;b.lastIndex=
0;b.test(c)&&(c=c.replace(b,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(c.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+c+")"),"function"===typeof a?g({"":f},""):f;throw new SyntaxError("JSON.parse");}})("undefined"!=typeof io?io:module.exports,"undefined"!==typeof JSON?JSON:void 0);
(function(h,e){var d=h.parser={},a=d.packets="disconnect,connect,heartbeat,message,json,event,ack,error,noop".split(","),g=d.reasons=["transport not supported","client not handshaken","unauthorized"],c=d.advice=["reconnect"],b=e.JSON,f=e.util.indexOf;d.encodePacket=function(d){var e=f(a,d.type),j=d.id||"",p=d.endpoint||"",h=d.ack,i=null;switch(d.type){case "error":var q=d.reason?f(g,d.reason):"",d=d.advice?f(c,d.advice):"";if(""!==q||""!==d)i=q+(""!==d?"+"+d:"");break;case "message":""!==d.data&&
(i=d.data);break;case "event":i={name:d.name};d.args&&d.args.length&&(i.args=d.args);i=b.stringify(i);break;case "json":i=b.stringify(d.data);break;case "connect":d.qs&&(i=d.qs);break;case "ack":i=d.ackId+(d.args&&d.args.length?"+"+b.stringify(d.args):"")}e=[e,j+("data"==h?"+":""),p];null!==i&&void 0!==i&&e.push(i);return e.join(":")};d.encodePayload=function(b){var c="";if(1==b.length)return b[0];for(var a=0,f=b.length;a<f;a++)c+="\ufffd"+b[a].length+"\ufffd"+b[a];return c};var i=/([^:]+):([0-9]+)?(\+)?:([^:]+)?:?([\s\S]*)?/;
d.decodePacket=function(f){var d=f.match(i);if(!d)return{};var e=d[2]||"",f=d[5]||"",h={type:a[d[1]],endpoint:d[4]||""};e&&(h.id=e,h.ack=d[3]?"data":!0);switch(h.type){case "error":d=f.split("+");h.reason=g[d[0]]||"";h.advice=c[d[1]]||"";break;case "message":h.data=f||"";break;case "event":try{var r=b.parse(f);h.name=r.name;h.args=r.args}catch(s){}h.args=h.args||[];break;case "json":try{h.data=b.parse(f)}catch(q){}break;case "connect":h.qs=f||"";break;case "ack":if(d=f.match(/^([0-9]+)(\+)?(.*)/))if(h.ackId=
d[1],h.args=[],d[3])try{h.args=d[3]?b.parse(d[3]):[]}catch(t){}}return h};d.decodePayload=function(b){if("\ufffd"==b.charAt(0)){for(var c=[],a=1,f="";a<b.length;a++)"\ufffd"==b.charAt(a)?(c.push(d.decodePacket(b.substr(a+1).substr(0,f))),a+=Number(f)+1,f=""):f+=b.charAt(a);return c}return[d.decodePacket(b)]}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(h,e){function d(a,d){this.socket=a;this.sessid=d}h.Transport=d;e.util.mixin(d,e.EventEmitter);d.prototype.onData=function(a){this.clearCloseTimeout();(this.socket.connected||this.socket.connecting||this.socket.reconnecting)&&this.setCloseTimeout();if(""!==a&&(a=e.parser.decodePayload(a))&&a.length)for(var d=0,c=a.length;d<c;d++)this.onPacket(a[d]);return this};d.prototype.onPacket=function(a){if("heartbeat"==a.type)return this.onHeartbeat();if("connect"==a.type&&""==a.endpoint)this.onConnect();
this.socket.onPacket(a);return this};d.prototype.setCloseTimeout=function(){if(!this.closeTimeout){var a=this;this.closeTimeout=setTimeout(function(){a.onDisconnect()},this.socket.closeTimeout)}};d.prototype.onDisconnect=function(){this.close&&this.open&&this.close();this.clearTimeouts();this.socket.onDisconnect();return this};d.prototype.onConnect=function(){this.socket.onConnect();return this};d.prototype.clearCloseTimeout=function(){this.closeTimeout&&(clearTimeout(this.closeTimeout),this.closeTimeout=
null)};d.prototype.clearTimeouts=function(){this.clearCloseTimeout();this.reopenTimeout&&clearTimeout(this.reopenTimeout)};d.prototype.packet=function(a){this.send(e.parser.encodePacket(a))};d.prototype.onHeartbeat=function(){this.packet({type:"heartbeat"})};d.prototype.onOpen=function(){this.open=!0;this.clearCloseTimeout();this.socket.onOpen()};d.prototype.onClose=function(){this.open=!1;this.socket.onClose();this.onDisconnect()};d.prototype.prepareUrl=function(){var a=this.socket.options;return this.scheme()+
"://"+a.host+":"+a.port+"/"+a.resource+"/"+e.protocol+"/"+this.name+"/"+this.sessid};d.prototype.ready=function(a,d){d.call(this)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(h,e,d){function a(c){this.options={port:80,secure:!1,document:"document"in d?document:!1,resource:"socket.io",transports:e.transports,"connect timeout":1E4,"try multiple transports":!0,reconnect:!0,"reconnection delay":500,"reconnection limit":Infinity,"reopen delay":3E3,"max reconnection attempts":10,"sync disconnect on unload":!0,"auto connect":!0,"flash policy port":10843};e.util.merge(this.options,c);this.reconnecting=this.connecting=this.open=this.connected=!1;this.namespaces={};this.buffer=
[];this.doBuffer=!1;if(this.options["sync disconnect on unload"]&&(!this.isXDomain()||e.util.ua.hasCORS)){var b=this;e.util.on(d,"beforeunload",function(){b.disconnectSync()},!1)}this.options["auto connect"]&&this.connect()}function g(){}h.Socket=a;e.util.mixin(a,e.EventEmitter);a.prototype.of=function(c){this.namespaces[c]||(this.namespaces[c]=new e.SocketNamespace(this,c),""!==c&&this.namespaces[c].packet({type:"connect"}));return this.namespaces[c]};a.prototype.publish=function(){this.emit.apply(this,
arguments);var c,b;for(b in this.namespaces)this.namespaces.hasOwnProperty(b)&&(c=this.of(b),c.$emit.apply(c,arguments))};a.prototype.handshake=function(c){function b(b){if(b instanceof Error)a.onError(b.message);else c.apply(null,b.split(":"))}var a=this,d=this.options,d=["http"+(d.secure?"s":"")+":/",d.host+":"+d.port,d.resource,e.protocol,e.util.query(this.options.query,"t="+ +new Date)].join("/");if(this.isXDomain()&&!e.util.ua.hasCORS){var h=document.getElementsByTagName("script")[0],l=document.createElement("script");
l.src=d+"&jsonp="+e.j.length;h.parentNode.insertBefore(l,h);e.j.push(function(c){b(c);l.parentNode.removeChild(l)})}else{var j=e.util.request();j.open("GET",d,!0);j.withCredentials=!0;j.onreadystatechange=function(){4==j.readyState&&(j.onreadystatechange=g,200==j.status?b(j.responseText):!a.reconnecting&&a.onError(j.responseText))};j.send(null)}};a.prototype.getTransport=function(c){for(var c=c||this.transports,b=0,a;a=c[b];b++)if(e.Transport[a]&&e.Transport[a].check(this)&&(!this.isXDomain()||e.Transport[a].xdomainCheck()))return new e.Transport[a](this,
this.sessionid);return null};a.prototype.connect=function(c){if(this.connecting)return this;var b=this;this.handshake(function(a,d,g,h){function j(c){b.transport&&b.transport.clearTimeouts();b.transport=b.getTransport(c);if(!b.transport)return b.publish("connect_failed");b.transport.ready(b,function(){b.connecting=!0;b.publish("connecting",b.transport.name);b.transport.open();b.options["connect timeout"]&&(b.connectTimeoutTimer=setTimeout(function(){if(!b.connected&&(b.connecting=!1,b.options["try multiple transports"])){b.remainingTransports||
(b.remainingTransports=b.transports.slice(0));for(var c=b.remainingTransports;0<c.length&&c.splice(0,1)[0]!=b.transport.name;);c.length?j(c):b.publish("connect_failed")}},b.options["connect timeout"]))})}b.sessionid=a;b.closeTimeout=1E3*g;b.heartbeatTimeout=1E3*d;b.transports=e.util.intersect(h.split(","),b.options.transports);j();b.once("connect",function(){clearTimeout(b.connectTimeoutTimer);c&&"function"==typeof c&&c()})});return this};a.prototype.packet=function(c){this.connected&&!this.doBuffer?
this.transport.packet(c):this.buffer.push(c);return this};a.prototype.setBuffer=function(c){this.doBuffer=c;!c&&this.connected&&this.buffer.length&&(this.transport.payload(this.buffer),this.buffer=[])};a.prototype.disconnect=function(){this.connected&&(this.open&&this.of("").packet({type:"disconnect"}),this.onDisconnect("booted"));return this};a.prototype.disconnectSync=function(){e.util.request().open("GET",this.resource+"/"+e.protocol+"/"+this.sessionid,!0);this.onDisconnect("booted")};a.prototype.isXDomain=
function(){var c=d.location.port||("https:"==d.location.protocol?443:80);return this.options.host!==d.location.hostname||this.options.port!=c};a.prototype.onConnect=function(){this.connected||(this.connected=!0,this.connecting=!1,this.doBuffer||this.setBuffer(!1),this.emit("connect"))};a.prototype.onOpen=function(){this.open=!0};a.prototype.onClose=function(){this.open=!1};a.prototype.onPacket=function(c){this.of(c.endpoint).onPacket(c)};a.prototype.onError=function(c){c&&c.advice&&this.options.reconnect&&
"reconnect"===c.advice&&this.connected&&(this.disconnect(),this.reconnect());this.publish("error",c&&c.reason?c.reason:c)};a.prototype.onDisconnect=function(c){var b=this.connected;this.open=this.connecting=this.connected=!1;b&&(this.transport.close(),this.transport.clearTimeouts(),this.publish("disconnect",c),"booted"!=c&&this.options.reconnect&&!this.reconnecting&&this.reconnect())};a.prototype.reconnect=function(){function c(){if(a.connected){for(var c in a.namespaces)a.namespaces.hasOwnProperty(c)&&
""!==c&&a.namespaces[c].packet({type:"connect"});a.publish("reconnect",a.transport.name,a.reconnectionAttempts)}clearTimeout(a.reconnectionTimer);a.removeListener("connect_failed",b);a.removeListener("connect",b);a.reconnecting=!1;delete a.reconnectionAttempts;delete a.reconnectionDelay;delete a.reconnectionTimer;delete a.redoTransports;a.options["try multiple transports"]=g}function b(){if(a.reconnecting){if(a.connected)return c();if(a.connecting&&a.reconnecting)return a.reconnectionTimer=setTimeout(b,
1E3);a.reconnectionAttempts++>=d?a.redoTransports?(a.publish("reconnect_failed"),c()):(a.on("connect_failed",b),a.options["try multiple transports"]=!0,a.transport=a.getTransport(),a.redoTransports=!0,a.connect()):(a.reconnectionDelay<e&&(a.reconnectionDelay*=2),a.connect(),a.publish("reconnecting",a.reconnectionDelay,a.reconnectionAttempts),a.reconnectionTimer=setTimeout(b,a.reconnectionDelay))}}this.reconnecting=!0;this.reconnectionAttempts=0;this.reconnectionDelay=this.options["reconnection delay"];
var a=this,d=this.options["max reconnection attempts"],g=this.options["try multiple transports"],e=this.options["reconnection limit"];this.options["try multiple transports"]=!1;this.reconnectionTimer=setTimeout(b,this.reconnectionDelay);this.on("connect",b)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(h,e){function d(d,c){this.socket=d;this.name=c||"";this.flags={};this.json=new a(this,"json");this.ackPackets=0;this.acks={}}function a(a,c){this.namespace=a;this.name=c}h.SocketNamespace=d;e.util.mixin(d,e.EventEmitter);d.prototype.$emit=e.EventEmitter.prototype.emit;d.prototype.of=function(){return this.socket.of.apply(this.socket,arguments)};d.prototype.packet=function(a){a.endpoint=this.name;this.socket.packet(a);this.flags={};return this};d.prototype.send=function(a,c){var b={type:this.flags.json?
"json":"message",data:a};"function"==typeof c&&(b.id=++this.ackPackets,b.ack=!0,this.acks[b.id]=c);return this.packet(b)};d.prototype.emit=function(a){var c=Array.prototype.slice.call(arguments,1),b=c[c.length-1],d={type:"event",name:a};"function"==typeof b&&(d.id=++this.ackPackets,d.ack="data",this.acks[d.id]=b,c=c.slice(0,c.length-1));d.args=c;return this.packet(d)};d.prototype.disconnect=function(){""===this.name?this.socket.disconnect():(this.packet({type:"disconnect"}),this.$emit("disconnect"));
return this};d.prototype.onPacket=function(a){function c(){b.packet({type:"ack",args:e.util.toArray(arguments),ackId:a.id})}var b=this;switch(a.type){case "connect":this.$emit("connect");break;case "disconnect":if(""===this.name)this.socket.onDisconnect(a.reason||"booted");else this.$emit("disconnect",a.reason);break;case "message":case "json":var d=["message",a.data];"data"==a.ack?d.push(c):a.ack&&this.packet({type:"ack",ackId:a.id});this.$emit.apply(this,d);break;case "event":d=[a.name].concat(a.args);
"data"==a.ack&&d.push(c);this.$emit.apply(this,d);break;case "ack":this.acks[a.ackId]&&(this.acks[a.ackId].apply(this,a.args),delete this.acks[a.ackId]);break;case "error":if(a.advice)this.socket.onError(a);else"unauthorized"==a.reason?this.$emit("connect_failed",a.reason):this.$emit("error",a.reason)}};a.prototype.send=function(){this.namespace.flags[this.name]=!0;this.namespace.send.apply(this.namespace,arguments)};a.prototype.emit=function(){this.namespace.flags[this.name]=!0;this.namespace.emit.apply(this.namespace,
arguments)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(h,e,d){function a(a){e.Transport.apply(this,arguments)}h.websocket=a;e.util.inherit(a,e.Transport);a.prototype.name="websocket";a.prototype.open=function(){var a=e.util.query(this.socket.options.query),c=this,b;b||(b=d.MozWebSocket||d.WebSocket);this.websocket=new b(this.prepareUrl()+a);this.websocket.onopen=function(){c.onOpen();c.socket.setBuffer(!1)};this.websocket.onmessage=function(a){c.onData(a.data)};this.websocket.onclose=function(){c.onClose();c.socket.setBuffer(!0)};this.websocket.onerror=
function(a){c.onError(a)};return this};a.prototype.send=function(a){this.websocket.send(a);return this};a.prototype.payload=function(a){for(var c=0,b=a.length;c<b;c++)this.packet(a[c]);return this};a.prototype.close=function(){this.websocket.close();return this};a.prototype.onError=function(a){this.socket.onError(a)};a.prototype.scheme=function(){return this.socket.options.secure?"wss":"ws"};a.check=function(){return"WebSocket"in d&&!("__addTask"in WebSocket)||"MozWebSocket"in d};a.xdomainCheck=function(){return!0};
e.transports.push("websocket")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
