/*! Socket.IO.js build:0.9.3, development. Copyright(c) 2011 LearnBoost <dev@learnboost.com> MIT Licensed */
(function(h,f){h.version="0.9.3";h.protocol=1;h.transports=[];h.j=[];h.sockets={};h.connect=function(a,d){var e=h.util.parseUri(a),c,b;f&&f.location&&(e.protocol=e.protocol||f.location.protocol.slice(0,-1),e.host=e.host||(f.document?f.document.domain:f.location.hostname),e.port=e.port||f.location.port);c=h.util.uniqueUri(e);var g={host:e.host,secure:"https"==e.protocol,port:e.port||("https"==e.protocol?443:80),query:e.query||""};h.util.merge(g,d);if(g["force new connection"]||!h.sockets[c])b=new h.Socket(g);
!g["force new connection"]&&b&&(h.sockets[c]=b);b=b||h.sockets[c];return b.of(1<e.path.length?e.path:"")}})("object"===typeof module?module.exports:this.io={},this);
(function(h,f){var a=h.util={},d=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,e="source,protocol,authority,userInfo,user,password,host,port,relative,path,directory,file,query,anchor".split(",");a.parseUri=function(b){for(var b=d.exec(b||""),g={},c=14;c--;)g[e[c]]=b[c]||"";return g};a.uniqueUri=function(b){var g=b.protocol,c=b.host,b=b.port;"document"in
f?(c=c||document.domain,b=b||("https"==g&&"https:"!==document.location.protocol?443:document.location.port)):(c=c||"localhost",!b&&"https"==g&&(b=443));return(g||"http")+"://"+c+":"+(b||80)};a.query=function(b,g){var c=a.chunkQuery(b||""),d=[];a.merge(c,a.chunkQuery(g||""));for(var e in c)c.hasOwnProperty(e)&&d.push(e+"="+c[e]);return d.length?"?"+d.join("&"):""};a.chunkQuery=function(b){for(var g={},b=b.split("&"),c=0,d=b.length,e;c<d;++c)e=b[c].split("="),e[0]&&(g[e[0]]=e[1]);return g};var c=!1;
a.load=function(b){if("document"in f&&"complete"===document.readyState||c)return b();a.on(f,"load",b,!1)};a.on=function(b,c,e,d){b.attachEvent?b.attachEvent("on"+c,e):b.addEventListener&&b.addEventListener(c,e,d)};a.request=function(b){if(b&&"undefined"!=typeof XDomainRequest)return new XDomainRequest;if("undefined"!=typeof XMLHttpRequest&&(!b||a.ua.hasCORS))return new XMLHttpRequest;if(!b)try{return new (window[["Active"].concat("Object").join("X")])("Microsoft.XMLHTTP")}catch(c){}return null};"undefined"!=
typeof window&&a.load(function(){c=!0});a.defer=function(b){if(!a.ua.webkit||"undefined"!=typeof importScripts)return b();a.load(function(){setTimeout(b,100)})};a.merge=function(b,c,e,d){var d=d||[],e="undefined"==typeof e?2:e,f;for(f in c)c.hasOwnProperty(f)&&0>a.indexOf(d,f)&&("object"!==typeof b[f]||!e?(b[f]=c[f],d.push(c[f])):a.merge(b[f],c[f],e-1,d));return b};a.mixin=function(b,c){a.merge(b.prototype,c.prototype)};a.inherit=function(b,c){function e(){}e.prototype=c.prototype;b.prototype=new e};
a.isArray=Array.isArray||function(b){return"[object Array]"===Object.prototype.toString.call(b)};a.intersect=function(b,c){for(var e=[],d=b.length>c.length?b:c,f=b.length>c.length?c:b,j=0,p=f.length;j<p;j++)~a.indexOf(d,f[j])&&e.push(f[j]);return e};a.indexOf=function(b,c,e){for(var d=b.length,e=0>e?0>e+d?0:e+d:e||0;e<d&&b[e]!==c;e++);return d<=e?-1:e};a.toArray=function(b){for(var c=[],e=0,d=b.length;e<d;e++)c.push(b[e]);return c};a.ua={};a.ua.hasCORS="undefined"!=typeof XMLHttpRequest&&function(){try{var b=
new XMLHttpRequest}catch(c){return!1}return void 0!=b.withCredentials}();a.ua.webkit="undefined"!=typeof navigator&&/webkit/i.test(navigator.userAgent)})("undefined"!=typeof io?io:module.exports,this);
(function(h,f){function a(){}h.EventEmitter=a;a.prototype.on=function(d,e){this.$events||(this.$events={});this.$events[d]?f.util.isArray(this.$events[d])?this.$events[d].push(e):this.$events[d]=[this.$events[d],e]:this.$events[d]=e;return this};a.prototype.addListener=a.prototype.on;a.prototype.once=function(d,e){function c(){b.removeListener(d,c);e.apply(this,arguments)}var b=this;c.listener=e;this.on(d,c);return this};a.prototype.removeListener=function(d,e){if(this.$events&&this.$events[d]){var c=
this.$events[d];if(f.util.isArray(c)){for(var b=-1,g=0,a=c.length;g<a;g++)if(c[g]===e||c[g].listener&&c[g].listener===e){b=g;break}if(0>b)return this;c.splice(b,1);c.length||delete this.$events[d]}else(c===e||c.listener&&c.listener===e)&&delete this.$events[d]}return this};a.prototype.removeAllListeners=function(d){this.$events&&this.$events[d]&&(this.$events[d]=null);return this};a.prototype.listeners=function(d){this.$events||(this.$events={});this.$events[d]||(this.$events[d]=[]);f.util.isArray(this.$events[d])||
(this.$events[d]=[this.$events[d]]);return this.$events[d]};a.prototype.emit=function(d){if(!this.$events)return!1;var e=this.$events[d];if(!e)return!1;var c=Array.prototype.slice.call(arguments,1);if("function"==typeof e)e.apply(this,c);else if(f.util.isArray(e))for(var e=e.slice(),b=0,g=e.length;b<g;b++)e[b].apply(this,c);else return!1;return!0}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(h,f){function a(b){return 10>b?"0"+b:b}function d(b){g.lastIndex=0;return g.test(b)?'"'+b.replace(g,function(b){var c=l[b];return"string"===typeof c?c:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function e(b,c){var g,f,l,h,o=i,m,k=c[b];k instanceof Date&&(k=isFinite(b.valueOf())?b.getUTCFullYear()+"-"+a(b.getUTCMonth()+1)+"-"+a(b.getUTCDate())+"T"+a(b.getUTCHours())+":"+a(b.getUTCMinutes())+":"+a(b.getUTCSeconds())+"Z":null);"function"===typeof j&&(k=j.call(c,b,
k));switch(typeof k){case "string":return d(k);case "number":return isFinite(k)?""+k:"null";case "boolean":case "null":return""+k;case "object":if(!k)return"null";i+=n;m=[];if("[object Array]"===Object.prototype.toString.apply(k)){h=k.length;for(g=0;g<h;g+=1)m[g]=e(g,k)||"null";l=0===m.length?"[]":i?"[\n"+i+m.join(",\n"+i)+"\n"+o+"]":"["+m.join(",")+"]";i=o;return l}if(j&&"object"===typeof j){h=j.length;for(g=0;g<h;g+=1)"string"===typeof j[g]&&(f=j[g],(l=e(f,k))&&m.push(d(f)+(i?": ":":")+l))}else for(f in k)Object.prototype.hasOwnProperty.call(k,
f)&&(l=e(f,k))&&m.push(d(f)+(i?": ":":")+l);l=0===m.length?"{}":i?"{\n"+i+m.join(",\n"+i)+"\n"+o+"}":"{"+m.join(",")+"}";i=o;return l}}if(f&&f.parse)return h.JSON={parse:f.parse,stringify:f.stringify};var c=h.JSON={},b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,i,n,l={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f",
"\r":"\\r",'"':'\\"',"\\":"\\\\"},j;c.stringify=function(b,c,d){var g;n=i="";if("number"===typeof d)for(g=0;g<d;g+=1)n+=" ";else"string"===typeof d&&(n=d);if((j=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return e("",{"":b})};c.parse=function(c,e){function d(b,c){var g,a,f=b[c];if(f&&"object"===typeof f)for(g in f)Object.prototype.hasOwnProperty.call(f,g)&&(a=d(f,g),void 0!==a?f[g]=a:delete f[g]);return e.call(b,c,f)}var g,c=""+c;b.lastIndex=
0;b.test(c)&&(c=c.replace(b,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(c.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return g=eval("("+c+")"),"function"===typeof e?d({"":g},""):g;throw new SyntaxError("JSON.parse");}})("undefined"!=typeof io?io:module.exports,"undefined"!==typeof JSON?JSON:void 0);
(function(h,f){var a=h.parser={},d=a.packets="disconnect,connect,heartbeat,message,json,event,ack,error,noop".split(","),e=a.reasons=["transport not supported","client not handshaken","unauthorized"],c=a.advice=["reconnect"],b=f.JSON,g=f.util.indexOf;a.encodePacket=function(a){var f=g(d,a.type),j=a.id||"",p=a.endpoint||"",h=a.ack,i=null;switch(a.type){case "error":var q=a.reason?g(e,a.reason):"",a=a.advice?g(c,a.advice):"";if(""!==q||""!==a)i=q+(""!==a?"+"+a:"");break;case "message":""!==a.data&&
(i=a.data);break;case "event":i={name:a.name};a.args&&a.args.length&&(i.args=a.args);i=b.stringify(i);break;case "json":i=b.stringify(a.data);break;case "connect":a.qs&&(i=a.qs);break;case "ack":i=a.ackId+(a.args&&a.args.length?"+"+b.stringify(a.args):"")}f=[f,j+("data"==h?"+":""),p];null!==i&&void 0!==i&&f.push(i);return f.join(":")};a.encodePayload=function(b){var c="";if(1==b.length)return b[0];for(var e=0,g=b.length;e<g;e++)c+="\ufffd"+b[e].length+"\ufffd"+b[e];return c};var i=/([^:]+):([0-9]+)?(\+)?:([^:]+)?:?([\s\S]*)?/;
a.decodePacket=function(g){var a=g.match(i);if(!a)return{};var f=a[2]||"",g=a[5]||"",h={type:d[a[1]],endpoint:a[4]||""};f&&(h.id=f,h.ack=a[3]?"data":!0);switch(h.type){case "error":a=g.split("+");h.reason=e[a[0]]||"";h.advice=c[a[1]]||"";break;case "message":h.data=g||"";break;case "event":try{var r=b.parse(g);h.name=r.name;h.args=r.args}catch(s){}h.args=h.args||[];break;case "json":try{h.data=b.parse(g)}catch(q){}break;case "connect":h.qs=g||"";break;case "ack":if(a=g.match(/^([0-9]+)(\+)?(.*)/))if(h.ackId=
a[1],h.args=[],a[3])try{h.args=a[3]?b.parse(a[3]):[]}catch(t){}}return h};a.decodePayload=function(b){if("\ufffd"==b.charAt(0)){for(var c=[],e=1,g="";e<b.length;e++)"\ufffd"==b.charAt(e)?(c.push(a.decodePacket(b.substr(e+1).substr(0,g))),e+=Number(g)+1,g=""):g+=b.charAt(e);return c}return[a.decodePacket(b)]}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(h,f){function a(a,e){this.socket=a;this.sessid=e}h.Transport=a;f.util.mixin(a,f.EventEmitter);a.prototype.onData=function(a){this.clearCloseTimeout();(this.socket.connected||this.socket.connecting||this.socket.reconnecting)&&this.setCloseTimeout();if(""!==a&&(a=f.parser.decodePayload(a))&&a.length)for(var e=0,c=a.length;e<c;e++)this.onPacket(a[e]);return this};a.prototype.onPacket=function(a){this.socket.setHeartbeatTimeout();if("heartbeat"==a.type)return this.onHeartbeat();if("connect"==
a.type&&""==a.endpoint)this.onConnect();this.socket.onPacket(a);return this};a.prototype.setCloseTimeout=function(){if(!this.closeTimeout){var a=this;this.closeTimeout=setTimeout(function(){a.onDisconnect()},this.socket.closeTimeout)}};a.prototype.onDisconnect=function(){this.close&&this.open&&this.close();this.clearTimeouts();this.socket.onDisconnect();return this};a.prototype.onConnect=function(){this.socket.onConnect();return this};a.prototype.clearCloseTimeout=function(){this.closeTimeout&&(clearTimeout(this.closeTimeout),
this.closeTimeout=null)};a.prototype.clearTimeouts=function(){this.clearCloseTimeout();this.reopenTimeout&&clearTimeout(this.reopenTimeout)};a.prototype.packet=function(a){this.send(f.parser.encodePacket(a))};a.prototype.onHeartbeat=function(){this.packet({type:"heartbeat"})};a.prototype.onOpen=function(){this.open=!0;this.clearCloseTimeout();this.socket.onOpen()};a.prototype.onClose=function(){this.open=!1;this.socket.onClose();this.onDisconnect()};a.prototype.prepareUrl=function(){var a=this.socket.options;
return this.scheme()+"://"+a.host+":"+a.port+"/"+a.resource+"/"+f.protocol+"/"+this.name+"/"+this.sessid};a.prototype.ready=function(a,e){e.call(this)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(h,f,a){function d(c){this.options={port:80,secure:!1,document:"document"in a?document:!1,resource:"socket.io",transports:f.transports,"connect timeout":1E4,"try multiple transports":!0,reconnect:!0,"reconnection delay":500,"reconnection limit":Infinity,"reopen delay":3E3,"max reconnection attempts":10,"sync disconnect on unload":!0,"auto connect":!0,"flash policy port":10843};f.util.merge(this.options,c);this.reconnecting=this.connecting=this.open=this.connected=!1;this.namespaces={};this.buffer=
[];this.doBuffer=!1;if(this.options["sync disconnect on unload"]&&(!this.isXDomain()||f.util.ua.hasCORS)){var b=this;f.util.on(a,"unload",function(){b.disconnectSync()},!1)}this.options["auto connect"]&&this.connect()}function e(){}h.Socket=d;f.util.mixin(d,f.EventEmitter);d.prototype.of=function(c){this.namespaces[c]||(this.namespaces[c]=new f.SocketNamespace(this,c),""!==c&&this.namespaces[c].packet({type:"connect"}));return this.namespaces[c]};d.prototype.publish=function(){this.emit.apply(this,
arguments);var c,b;for(b in this.namespaces)this.namespaces.hasOwnProperty(b)&&(c=this.of(b),c.$emit.apply(c,arguments))};d.prototype.handshake=function(c){function b(b){if(b instanceof Error)a.onError(b.message);else c.apply(null,b.split(":"))}var a=this,d=this.options,d=["http"+(d.secure?"s":"")+":/",d.host+":"+d.port,d.resource,f.protocol,f.util.query(this.options.query,"t="+ +new Date)].join("/");if(this.isXDomain()&&!f.util.ua.hasCORS){var h=document.getElementsByTagName("script")[0],l=document.createElement("script");
l.src=d+"&jsonp="+f.j.length;h.parentNode.insertBefore(l,h);f.j.push(function(c){b(c);l.parentNode.removeChild(l)})}else{var j=f.util.request();j.open("GET",d,!0);j.withCredentials=!0;j.onreadystatechange=function(){4==j.readyState&&(j.onreadystatechange=e,200==j.status?b(j.responseText):!a.reconnecting&&a.onError(j.responseText))};j.send(null)}};d.prototype.getTransport=function(c){for(var c=c||this.transports,b=0,a;a=c[b];b++)if(f.Transport[a]&&f.Transport[a].check(this)&&(!this.isXDomain()||f.Transport[a].xdomainCheck()))return new f.Transport[a](this,
this.sessionid);return null};d.prototype.connect=function(c){if(this.connecting)return this;var b=this;this.handshake(function(a,e,d,h){function j(c){b.transport&&b.transport.clearTimeouts();b.transport=b.getTransport(c);if(!b.transport)return b.publish("connect_failed");b.transport.ready(b,function(){b.connecting=!0;b.publish("connecting",b.transport.name);b.transport.open();b.options["connect timeout"]&&(b.connectTimeoutTimer=setTimeout(function(){if(!b.connected&&(b.connecting=!1,b.options["try multiple transports"])){b.remainingTransports||
(b.remainingTransports=b.transports.slice(0));for(var c=b.remainingTransports;0<c.length&&c.splice(0,1)[0]!=b.transport.name;);c.length?j(c):b.publish("connect_failed")}},b.options["connect timeout"]))})}b.sessionid=a;b.closeTimeout=1E3*d;b.heartbeatTimeout=1E3*e;b.transports=h?f.util.intersect(h.split(","),b.options.transports):b.options.transports;b.setHeartbeatTimeout();j(b.transports);b.once("connect",function(){clearTimeout(b.connectTimeoutTimer);c&&"function"==typeof c&&c()})});return this};
d.prototype.setHeartbeatTimeout=function(){clearTimeout(this.heartbeatTimeoutTimer);var c=this;this.heartbeatTimeoutTimer=setTimeout(function(){c.transport.onClose()},this.heartbeatTimeout)};d.prototype.packet=function(c){this.connected&&!this.doBuffer?this.transport.packet(c):this.buffer.push(c);return this};d.prototype.setBuffer=function(c){this.doBuffer=c;!c&&this.connected&&this.buffer.length&&(this.transport.payload(this.buffer),this.buffer=[])};d.prototype.disconnect=function(){if(this.connected||
this.connecting)this.open&&this.of("").packet({type:"disconnect"}),this.onDisconnect("booted");return this};d.prototype.disconnectSync=function(){f.util.request().open("GET",this.resource+"/"+f.protocol+"/"+this.sessionid,!0);this.onDisconnect("booted")};d.prototype.isXDomain=function(){var c=a.location.port||("https:"==a.location.protocol?443:80);return this.options.host!==a.location.hostname||this.options.port!=c};d.prototype.onConnect=function(){this.connected||(this.connected=!0,this.connecting=
!1,this.doBuffer||this.setBuffer(!1),this.emit("connect"))};d.prototype.onOpen=function(){this.open=!0};d.prototype.onClose=function(){this.open=!1;clearTimeout(this.heartbeatTimeoutTimer)};d.prototype.onPacket=function(c){this.of(c.endpoint).onPacket(c)};d.prototype.onError=function(c){if(c&&c.advice&&"reconnect"===c.advice&&(this.connected||this.connecting))this.disconnect(),this.options.reconnect&&this.reconnect();this.publish("error",c&&c.reason?c.reason:c)};d.prototype.onDisconnect=function(c){var b=
this.connected,a=this.connecting;this.open=this.connecting=this.connected=!1;if(b||a)this.transport.close(),this.transport.clearTimeouts(),b&&(this.publish("disconnect",c),"booted"!=c&&this.options.reconnect&&!this.reconnecting&&this.reconnect())};d.prototype.reconnect=function(){function c(){if(a.connected){for(var c in a.namespaces)a.namespaces.hasOwnProperty(c)&&""!==c&&a.namespaces[c].packet({type:"connect"});a.publish("reconnect",a.transport.name,a.reconnectionAttempts)}clearTimeout(a.reconnectionTimer);
a.removeListener("connect_failed",b);a.removeListener("connect",b);a.reconnecting=!1;delete a.reconnectionAttempts;delete a.reconnectionDelay;delete a.reconnectionTimer;delete a.redoTransports;a.options["try multiple transports"]=d}function b(){if(a.reconnecting){if(a.connected)return c();if(a.connecting&&a.reconnecting)return a.reconnectionTimer=setTimeout(b,1E3);a.reconnectionAttempts++>=e?a.redoTransports?(a.publish("reconnect_failed"),c()):(a.on("connect_failed",b),a.options["try multiple transports"]=
!0,a.transport=a.getTransport(),a.redoTransports=!0,a.connect()):(a.reconnectionDelay<f&&(a.reconnectionDelay*=2),a.connect(),a.publish("reconnecting",a.reconnectionDelay,a.reconnectionAttempts),a.reconnectionTimer=setTimeout(b,a.reconnectionDelay))}}this.reconnecting=!0;this.reconnectionAttempts=0;this.reconnectionDelay=this.options["reconnection delay"];var a=this,e=this.options["max reconnection attempts"],d=this.options["try multiple transports"],f=this.options["reconnection limit"];this.options["try multiple transports"]=
!1;this.reconnectionTimer=setTimeout(b,this.reconnectionDelay);this.on("connect",b)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(h,f){function a(a,c){this.socket=a;this.name=c||"";this.flags={};this.json=new d(this,"json");this.ackPackets=0;this.acks={}}function d(a,c){this.namespace=a;this.name=c}h.SocketNamespace=a;f.util.mixin(a,f.EventEmitter);a.prototype.$emit=f.EventEmitter.prototype.emit;a.prototype.of=function(){return this.socket.of.apply(this.socket,arguments)};a.prototype.packet=function(a){a.endpoint=this.name;this.socket.packet(a);this.flags={};return this};a.prototype.send=function(a,c){var b={type:this.flags.json?
"json":"message",data:a};"function"==typeof c&&(b.id=++this.ackPackets,b.ack=!0,this.acks[b.id]=c);return this.packet(b)};a.prototype.emit=function(a){var c=Array.prototype.slice.call(arguments,1),b=c[c.length-1],d={type:"event",name:a};"function"==typeof b&&(d.id=++this.ackPackets,d.ack="data",this.acks[d.id]=b,c=c.slice(0,c.length-1));d.args=c;return this.packet(d)};a.prototype.disconnect=function(){""===this.name?this.socket.disconnect():(this.packet({type:"disconnect"}),this.$emit("disconnect"));
return this};a.prototype.onPacket=function(a){function c(){b.packet({type:"ack",args:f.util.toArray(arguments),ackId:a.id})}var b=this;switch(a.type){case "connect":this.$emit("connect");break;case "disconnect":if(""===this.name)this.socket.onDisconnect(a.reason||"booted");else this.$emit("disconnect",a.reason);break;case "message":case "json":var d=["message",a.data];"data"==a.ack?d.push(c):a.ack&&this.packet({type:"ack",ackId:a.id});this.$emit.apply(this,d);break;case "event":d=[a.name].concat(a.args);
"data"==a.ack&&d.push(c);this.$emit.apply(this,d);break;case "ack":this.acks[a.ackId]&&(this.acks[a.ackId].apply(this,a.args),delete this.acks[a.ackId]);break;case "error":if(a.advice)this.socket.onError(a);else"unauthorized"==a.reason?this.$emit("connect_failed",a.reason):this.$emit("error",a.reason)}};d.prototype.send=function(){this.namespace.flags[this.name]=!0;this.namespace.send.apply(this.namespace,arguments)};d.prototype.emit=function(){this.namespace.flags[this.name]=!0;this.namespace.emit.apply(this.namespace,
arguments)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(h,f,a){function d(a){f.Transport.apply(this,arguments)}h.websocket=d;f.util.inherit(d,f.Transport);d.prototype.name="websocket";d.prototype.open=function(){var d=f.util.query(this.socket.options.query),c=this,b;b||(b=a.MozWebSocket||a.WebSocket);this.websocket=new b(this.prepareUrl()+d);this.websocket.onopen=function(){c.onOpen();c.socket.setBuffer(!1)};this.websocket.onmessage=function(a){c.onData(a.data)};this.websocket.onclose=function(){c.onClose();c.socket.setBuffer(!0)};this.websocket.onerror=
function(a){c.onError(a)};return this};d.prototype.send=function(a){this.websocket.send(a);return this};d.prototype.payload=function(a){for(var c=0,b=a.length;c<b;c++)this.packet(a[c]);return this};d.prototype.close=function(){this.websocket.close();return this};d.prototype.onError=function(a){this.socket.onError(a)};d.prototype.scheme=function(){return this.socket.options.secure?"wss":"ws"};d.check=function(){return"WebSocket"in a&&!("__addTask"in WebSocket)||"MozWebSocket"in a};d.xdomainCheck=function(){return!0};
f.transports.push("websocket")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
